<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Recalculate</name>
   <tag></tag>
   <elementGuidId>2f2cb86e-4d55-4565-bd9c-e6cbb5980811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='NOSAVEButtonISOReplacementCost_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEButtonISOReplacementCost_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8aea020-deda-468e-9ed3-258a3533e988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn buttonWidget ISiA-PrimaryButton</value>
      <webElementGuid>2811b3e3-6554-47de-bcb4-7c0fcc4f0d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>073967fe-b28d-4ee7-80e4-a759526be740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if ((typeof this === 'undefined' || typeof this.id === 'undefined' || this.id=='' || DblClkTrap(this.id,'set'))) { LookupButtonClickJS('751','3','reusableModalBody','https://cypresstest.cogisi.com/is/root/','1','ISO360');  };</value>
      <webElementGuid>f6d2fe52-a882-47d8-8762-2ef28f0ac515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEButtonISOReplacementCost_1</value>
      <webElementGuid>79c12d06-b739-4095-b1e9-03ac60a11198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEButtonISOReplacementCost_1</value>
      <webElementGuid>94956053-4812-4ea6-8a07-c5f1c90a9fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recalculate</value>
      <webElementGuid>61bf9720-1a5c-4384-a09a-ed90da642b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEButtonISOReplacementCost_1&quot;)</value>
      <webElementGuid>df35b0a6-84d4-4664-a741-b3d221de1e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test (1)</value>
      <webElementGuid>df5da9da-9d83-4903-aaf3-377411a443ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='NOSAVEButtonISOReplacementCost_1']</value>
      <webElementGuid>0d3e6a06-825f-45c9-93f2-882eedbd09c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ISOReplacementCost_1']/div/div/button</value>
      <webElementGuid>6a22ad28-a28f-4fa9-aa00-821a505170c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO 360Value Replacement Cost Calculation'])[1]/following::button[1]</value>
      <webElementGuid>b8b54693-273e-4187-883a-24c71f567097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replacement Cost'])[1]/following::button[1]</value>
      <webElementGuid>e196bccd-d04b-4834-a305-88e334beb4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating Variables'])[1]/preceding::button[1]</value>
      <webElementGuid>11f3941c-4e80-400f-80f4-738421de9eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Burglar Alarm'])[1]/preceding::button[1]</value>
      <webElementGuid>062663af-9c43-487a-847c-a5e4688abb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recalculate']/parent::*</value>
      <webElementGuid>d9640c7b-1721-47aa-bae4-725a97d3f5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>28c77b5d-2f03-46f0-8467-36a12201c4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'NOSAVEButtonISOReplacementCost_1' and @id = 'NOSAVEButtonISOReplacementCost_1' and (text() = 'Recalculate' or . = 'Recalculate')]</value>
      <webElementGuid>9daeee48-a9a1-463c-aadc-ffd4fd9c7210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
