<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PolicyNumber</name>
   <tag></tag>
   <elementGuidId>2b60ba96-0dd8-404f-a44b-877651ab945c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='acct_header_table']/tbody/tr/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a532dd2c-613e-4136-ad99-034f219d071f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DarkLink</value>
      <webElementGuid>58db251e-b16d-4632-941d-0cda47e19304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>Content</value>
      <webElementGuid>9fe4a464-f304-48be-acdb-0677112d395a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>main.cfm?view=acct&amp;pages=moneysummary&amp;PolicyID=300310&amp;DisplayAcctFrame=false</value>
      <webElementGuid>54b46be2-2fca-4f79-af0b-63603476a372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IFD4105919-00</value>
      <webElementGuid>00a0bee3-73c1-47b1-b03d-3520027f0493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicyDetailsMainDiv&quot;)/div[@class=&quot;ISiWhiteCanvasHeader&quot;]/table[@id=&quot;acct_header_table&quot;]/tbody[1]/tr[1]/td[@class=&quot;ISiPolicyHeader&quot;]/a[@class=&quot;DarkLink&quot;]</value>
      <webElementGuid>5a07383a-cace-4693-895b-f322ca306f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test (1)</value>
      <webElementGuid>3e03049d-b874-4e3d-b9e1-921beb1b0595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='acct_header_table']/tbody/tr/td[4]/a</value>
      <webElementGuid>b10ea656-53d5-4847-9cde-e7db84310916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'IFD4105919-00')]</value>
      <webElementGuid>81e97b7a-80c8-470d-8ab1-03e8493b2198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FLORIDA Dwelling'])[1]/preceding::a[1]</value>
      <webElementGuid>3cc74406-5841-4b53-8922-4060df78e1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cypress Property &amp; Casualty Insurance Company'])[1]/preceding::a[1]</value>
      <webElementGuid>59ebaf18-0d28-48a8-a040-9b932ca1a55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IFD4105919-00']/parent::*</value>
      <webElementGuid>fab6c979-e76b-4e4b-8fc1-7baf79bdba6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'main.cfm?view=acct&amp;pages=moneysummary&amp;PolicyID=300310&amp;DisplayAcctFrame=false')]</value>
      <webElementGuid>fb8dbfc1-1d41-47e5-8e3f-0a8b642d7d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>05a6deb7-becc-4d3c-bae3-8da06486dc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'main.cfm?view=acct&amp;pages=moneysummary&amp;PolicyID=300310&amp;DisplayAcctFrame=false' and (text() = 'IFD4105919-00' or . = 'IFD4105919-00')]</value>
      <webElementGuid>c3575c9f-6d17-4c18-b831-d5421397f26c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
