<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Permitted Incidental Occupancy - Limit</name>
   <tag></tag>
   <elementGuidId>5ad8adbd-9f46-4e7c-9369-7f122d4cb090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IncidentalOccupancyLimit_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IncidentalOccupancyLimit_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c0ff935-1b0d-4f3e-8018-00f27ea98ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e1e6d34-c6ff-4738-b80f-b6ec93790ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textWidget ISiA-Force-Uppercase</value>
      <webElementGuid>1f0427f4-8b01-4843-afca-9dc7886911d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IncidentalOccupancyLimit_1</value>
      <webElementGuid>f36cf958-153a-4700-aa11-5a7530aedfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75f4329e-3a6e-4beb-967e-0481bb4ef8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IncidentalOccupancyLimit_1</value>
      <webElementGuid>348a8360-a78f-45db-b8b7-1e7680a7a1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validateTextInput(this);   CheckRequired(false);</value>
      <webElementGuid>a47fa7e3-1244-4ad6-a064-2b1a738a9038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>26cbc810-ade8-4ec0-8513-14818ed3d905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputtype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>fc93432d-6521-4bfe-9f15-081788024544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uppercase</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>416a5aa2-a32e-452f-a0cf-7eea953bec44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>issensitive</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d947fcef-55a7-44c0-8778-34baf72861a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchclass</name>
      <type>Main</type>
      <value>Any</value>
      <webElementGuid>0477d85a-3963-4aa0-9fb3-ff61897f05b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskText(this, event)</value>
      <webElementGuid>5c32cb04-24a7-4e40-a39e-e98fbe9d72f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IncidentalOccupancyLimit_1&quot;)</value>
      <webElementGuid>093bef46-15f1-4f29-a3e4-32dd3dc151ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>d5b922dc-1ed9-4ba6-a511-2d2866d4b56c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IncidentalOccupancyLimit_1']</value>
      <webElementGuid>15164bc6-7d72-4a16-898e-4b503748ad84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-IncidentalOccupancyLimit_1']/div/input</value>
      <webElementGuid>f841d625-36eb-42e4-a2f0-5098f138b577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div[6]/div/input</value>
      <webElementGuid>7ccf12c8-7d5b-4e89-8e55-e3ab548d3a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'IncidentalOccupancyLimit_1' and @name = 'IncidentalOccupancyLimit_1']</value>
      <webElementGuid>9e1e8df3-e8fc-42ec-9c48-6cb0d9874594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
