<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PreviousZip</name>
   <tag></tag>
   <elementGuidId>47222f53-1942-4671-ae73-b1271a4c28a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PreviousZip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PreviousZip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e7af0a7-a221-4604-9f7f-1f02fa600ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d84f2a60-33b2-443c-9ccd-057f49ce8ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberAddressWidget</value>
      <webElementGuid>d3c4dd1f-4a9e-4887-bc3a-a96f937f6167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip Code</value>
      <webElementGuid>57c20d20-7e7a-4e35-bc27-8ebdc02f731d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d8ce7549-e4e4-4a3a-b1e3-0e5ee8d6a398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PreviousZip</value>
      <webElementGuid>09209b3d-240d-41cc-b956-dde988f8b8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PreviousZip</value>
      <webElementGuid>b243d126-2529-4bcd-b08b-4935d707edc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);ISiA_QuickZipCheck(this);USPSRealtimeAddressValidation('a82741540573558027i15151613s3902970422694160i54330','https://cypresstest.cogisi.com/is/','200240','Previous','','Zip',0,0);</value>
      <webElementGuid>011e17b4-2bb7-4f68-8253-befa402d58f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Previous').value='0';</value>
      <webElementGuid>04d6c77c-70ae-4942-b8fe-df0ddfb4a06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>PositiveInteger</value>
      <webElementGuid>0bcfa6a7-ffdf-47cd-a791-018c9a2a7355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PreviousZip&quot;)</value>
      <webElementGuid>97d78d30-71ca-4a67-a499-e7c205fe1d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>244f1686-ab35-4473-a6c7-a535ce625d0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PreviousZip']</value>
      <webElementGuid>af05513f-9c4c-4f8c-92c0-bd4e38f01f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-PreviousZip']/div/input</value>
      <webElementGuid>b7ce3f7f-6da3-48de-b210-4d8536f703ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div/div/div/div[5]/div[4]/div/input</value>
      <webElementGuid>fe573f32-c384-4e3e-b065-113ce993520d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Zip Code' and @name = 'PreviousZip' and @id = 'PreviousZip']</value>
      <webElementGuid>889840a3-7606-4582-8823-f99321263e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
