<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Zip Code_ApplicantZip</name>
   <tag></tag>
   <elementGuidId>5ebf8d3c-cbd4-4098-a422-3b5998ccf9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantZip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ApplicantZip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a7302f2-69cd-4c63-8d1c-814e61331e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6add8004-ee58-46c0-968a-2df1e7d947c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantZip</value>
      <webElementGuid>c0634ee8-2992-4b7f-808f-c16591eaa031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantZip</value>
      <webElementGuid>66dc907c-8d67-4710-a79e-5b21d3e5ff2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>720d3b8c-eea5-48b4-b8a2-2e9b54019753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8b3d417a-9235-4d7c-934d-0baa2fff3c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>chkZip(this);zipChangeHandler(this.value, true);GMJSDataManager('0',document.getElementById('RealtimeGeocodingProviderSelector').value,'^ConstructionYear_1|');MakeVerifyStreetAddressCall('https://cypresstest.cogisi.com/is/',this.form,'Applicant','','',getMostRelevantPolicyTypeCodeValue(document.getElementById('PolicyTypeCode'),'',''),'0'); </value>
      <webElementGuid>744afe4c-578d-4e6a-bc67-2416f58e5eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;  </value>
      <webElementGuid>8a5c8f53-83ce-4ab6-8dbf-290c19091593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#####</value>
      <webElementGuid>8e50d7a3-295e-4e3f-808b-a5e7e6890197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantZip&quot;)</value>
      <webElementGuid>d71985e0-3b1b-4cac-bf40-820caa47b92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>fee9db4e-0f7c-4664-8dee-1a9bf0005af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantZip']</value>
      <webElementGuid>cf2cd375-2fbd-4cb2-9b19-bafc5b24547f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='QuoteAddress5']/td[2]/input</value>
      <webElementGuid>cd194ed8-c456-4fc4-a084-a16ec5e7b7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/input</value>
      <webElementGuid>cd7f37f0-5554-4bff-a75a-dca0ff722c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ApplicantZip' and @name = 'ApplicantZip' and @placeholder = '#####']</value>
      <webElementGuid>7980a50e-a762-45bd-ab9d-405c74906eb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
