<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_ApplicantHomePhonezzzz1</name>
   <tag></tag>
   <elementGuidId>3ba882a2-fa51-45ab-af76-26906aa3bc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantHomePhonezzzz1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ApplicantHomePhonezzzz1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5049315-1819-46a5-ac89-0125da7d80df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fe60528-5bc3-4eac-9350-f38de0537a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>ddd-ddd-dddd</value>
      <webElementGuid>3ea1352c-fb84-4f41-a2a1-d3c20eb11de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control phoneWidget</value>
      <webElementGuid>034a2c2d-bf67-458f-9e2c-6cf39a9ba695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantHomePhonezzzz1</value>
      <webElementGuid>aaad0336-2c91-4b96-85f8-9ffdabcaf748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>654b9f1e-7ceb-4434-a8a4-8f7ed0476312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantHomePhonezzzz1</value>
      <webElementGuid>c5f5ef56-a956-4a7b-82e5-cee7ad69dbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validatePhoneNumber(this);</value>
      <webElementGuid>d7722017-a4f5-4597-a3c4-bf2667df6956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskPhoneNumber(this, event);</value>
      <webElementGuid>85090d23-0289-4572-8bf6-a369790d3d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantHomePhonezzzz1&quot;)</value>
      <webElementGuid>188f547e-fa2f-4077-ae4b-32404a2cdc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>794a7ec2-bd5e-4cd4-a4b8-41963f77b29c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantHomePhonezzzz1']</value>
      <webElementGuid>6ee95055-752b-4b58-b705-313d70641ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ApplicantHomePhonezzzz1']/input</value>
      <webElementGuid>a072e55c-11f7-440b-b007-369939fca5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>012a1545-ad02-4d41-863e-9cfc14ed838d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantHomePhonezzzz1' and @id = 'ApplicantHomePhonezzzz1']</value>
      <webElementGuid>58ae10c7-0abe-4df2-9dea-5912eb4b9cba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
