<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DwellingHomeownersHomeowners - Legac_cd4163</name>
   <tag></tag>
   <elementGuidId>05e8c722-c2f0-430f-9814-277351f27b5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PolicyTypeCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PolicyTypeCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4766f1bf-5119-49b5-bb56-e328725d5d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PolicyTypeCode</value>
      <webElementGuid>5083bcb0-f264-4f53-b7b6-feddce08c570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PolicyTypeCode</value>
      <webElementGuid>4458d182-2d37-4ede-9902-7f9b387011dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>; chkQuotes(this) </value>
      <webElementGuid>2d603d19-5a50-4bd2-b281-ddfaec6b72ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ProcessOverrideDisableGMGeocodeRequest(this[this.selectedIndex].value,document.getElementById('VeriskSupportedPolicyTypeCodeList').value,'');QuickQuoteSettings(this);;makeGetVeriskStatusJSCall();</value>
      <webElementGuid>3b829a7d-fbdb-4583-9889-106aa001bdde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DwellingHomeownersHomeowners - LegacyCondoCondo - Legacy</value>
      <webElementGuid>2ca75cb2-7818-408f-a72a-df3ec8bf2a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicyTypeCode&quot;)</value>
      <webElementGuid>dbd682ae-4cd4-4cc4-b56f-199d53a12546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>2747c70f-b0e9-4ad9-a2de-9d19b8f1d801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PolicyTypeCode']</value>
      <webElementGuid>1c4fad8e-ea76-41e8-b49a-1bfc1c6c9f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='StartANewQuoteFormTable']/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>ca7ad647-c6ae-407f-9a6f-2132fe0f20d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Type:'])[1]/following::select[1]</value>
      <webElementGuid>dfd1e558-ca69-4b33-b782-e1ed726f3376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name:'])[1]/preceding::select[1]</value>
      <webElementGuid>aeb9fb13-4aec-4609-8712-4369e720190c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/select</value>
      <webElementGuid>864a1de5-c6d7-46cb-80c2-3982d75bdc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PolicyTypeCode' and @name = 'PolicyTypeCode' and (text() = 'DwellingHomeownersHomeowners - LegacyCondoCondo - Legacy' or . = 'DwellingHomeownersHomeowners - LegacyCondoCondo - Legacy')]</value>
      <webElementGuid>6e267cf5-aca6-4156-b2e0-abb943a149be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
