<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AdditionalIntrestButton</name>
   <tag></tag>
   <elementGuidId>f6bc5c63-b69e-460d-9c3c-9694083d7b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addDetailButtonAdditionalInterests_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addDetailButtonAdditionalInterests_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79c73825-6912-47c2-8bea-d3c273d9aeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn ISiA-PrimaryButton ISiA-SmallButton</value>
      <webElementGuid>a7ed0011-d3bf-4183-a9cf-34c6712b86ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6dc3474-40b6-425e-94b5-bc5694b7a735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addDetailButtonAdditionalInterests_1</value>
      <webElementGuid>955c8154-4d9a-4dcc-938d-2fb30c9936c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>2c76287a-5d26-46d1-878d-9ac0e943db9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AddAccordionPage('AdditionalInterests', '_1', 801, 2, 1, 1, 'detail', 'DeleteButtonJS(this, [AdditionalInterests_1, NOSAVEShowDetailItemAdditionalInterests_1], &quot;_1&quot;, )','https://cypresstest.cogisi.com/is/root/','internal')</value>
      <webElementGuid>f380134b-3eb5-419a-8976-5745fd25b905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addDetailButtonAdditionalInterests_1&quot;)</value>
      <webElementGuid>71222156-b156-40f4-b95d-7ac168f76a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>d31427b8-e1a3-406a-b3f7-18b56edaeb3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addDetailButtonAdditionalInterests_1']</value>
      <webElementGuid>76777f3d-1f07-4511-94dd-898365f669be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-AdditionalInterests_1']/div[3]/div/div/div[2]/input</value>
      <webElementGuid>50c02f22-441a-47f0-a53e-d0854d316a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4c33a354-f3a8-4223-b8df-f521dc137eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'addDetailButtonAdditionalInterests_1']</value>
      <webElementGuid>f66f62ea-6df3-4889-854b-f57903bc63d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
