<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Authorize Credit Card</name>
   <tag></tag>
   <elementGuidId>147fa411-5810-40c4-b135-d192e06e35ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='NOSAVEButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea22764b-ef35-438c-a2d5-3df542d2395e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn buttonWidget ISiA-PrimaryButton mb-3 ModalButtonMargin3</value>
      <webElementGuid>a3a1c0de-092f-406c-8625-75832edf2810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe2f8ad5-d6cd-4697-b957-c87f7d400b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Authorize Credit Card</value>
      <webElementGuid>ec13243e-f167-4c0e-bf0e-4125b6165e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if ((typeof this === 'undefined' || typeof this.id === 'undefined' || this.id=='' || DblClkTrap(this.id,'set'))) { PostCC(this);  };</value>
      <webElementGuid>53e58258-1967-420c-9af5-f34236c373aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEButton</value>
      <webElementGuid>151f29c8-7a64-4769-9406-b59a3b520255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEButton</value>
      <webElementGuid>f2a09d72-b307-4a8e-8cb3-5a00dbcd8ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorize Credit Card</value>
      <webElementGuid>2327c175-7c0b-462e-a4ae-edea050b14e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEButton&quot;)</value>
      <webElementGuid>a9b32209-8ebb-4f39-b2bd-cd609cb48fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO3/Page_/iframe_Enter Credit Card Information_reusab_436954</value>
      <webElementGuid>780de144-60d3-4138-a48a-c3b747a50b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='NOSAVEButton']</value>
      <webElementGuid>69315c3a-ff6a-45e2-bb4b-d671f74bb4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-2856']/button</value>
      <webElementGuid>b03e2a2d-e90a-4f51-9010-91d4bd8e33b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Security Code'])[1]/following::button[1]</value>
      <webElementGuid>4b6f9419-645c-4295-adf2-917c0468f569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Expiration Date'])[1]/following::button[1]</value>
      <webElementGuid>682880f6-e8c6-4cba-906f-f8e868b1e7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debugging information and Tools'])[1]/preceding::button[1]</value>
      <webElementGuid>e560b9c8-8e41-4125-833d-c670b24bdfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log'])[1]/preceding::button[2]</value>
      <webElementGuid>9b8b01a3-126b-4e2c-bb36-6f74281a652c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Authorize Credit Card']/parent::*</value>
      <webElementGuid>d6c9341c-28fd-4876-a7ef-25bf66ccbe16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2c5a3685-9902-413d-bf28-935973c14a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'NOSAVEButton' and @id = 'NOSAVEButton' and (text() = 'Authorize Credit Card' or . = 'Authorize Credit Card')]</value>
      <webElementGuid>ef51da41-6dc0-4196-b8ac-15d2f54dac95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
