<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Enter Credit Card Information_reusab_436954</name>
   <tag></tag>
   <elementGuidId>34d63add-0a28-4980-901f-ee220caf9311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='reusableiFrameBody']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reusableiFrameBody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>707e7891-6137-497f-830e-6e32d4e1793d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body modal-body-nopadding modal-reusableModalBody ModalSizing1</value>
      <webElementGuid>257be76e-97d9-4653-9f12-81daf9d14203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reusableiFrameBody</value>
      <webElementGuid>3f73d7a5-3387-4525-b409-97bef0ed7cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reusableiFrameBody</value>
      <webElementGuid>70171c26-a089-4854-84f7-04ab91cf6171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7decb4a7-1cd3-449a-a0d4-2f38afc818dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>pageLoad.cfm?AuthToken=a66704507525507606i32861111s2542370082880991i37322&amp;bIncludeBootstrap=true&amp;PageID=90&amp;AreaID=2&amp;ParentID=NOSAVEButtonnone&amp;ParentText=Update%20Credit%20Card%20Information&amp;JSResize=reusableiFrameBody~height~parent.window%7CPageHeight%7C75%7C1000%5EreusableiFrameParentContentDiv~maxHeight~parent%7CreusableiFrameBodyParent~~parent+reusableiFrameBodyTitle~~parent%7C7%7C10&amp;AdditionalAction=1</value>
      <webElementGuid>4e53f74a-d660-4b9e-9fb8-7f069e4cd5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reusableiFrameBody&quot;)</value>
      <webElementGuid>19c84a51-6c7e-455b-80fa-5449ed7b6a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO3/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>76e19d2c-1416-4c76-a12a-754492d3e4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='reusableiFrameBody']</value>
      <webElementGuid>6c857cef-9e59-4b6f-a108-81a0a4a74201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reusableiFrameBodyParent']/div/iframe</value>
      <webElementGuid>11bd655a-da78-4ec7-878a-799a8cf5e55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/iframe</value>
      <webElementGuid>63c1a6fa-0e70-4da1-bfc3-a9b27d2dfe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'reusableiFrameBody' and @id = 'reusableiFrameBody' and @src = 'pageLoad.cfm?AuthToken=a66704507525507606i32861111s2542370082880991i37322&amp;bIncludeBootstrap=true&amp;PageID=90&amp;AreaID=2&amp;ParentID=NOSAVEButtonnone&amp;ParentText=Update%20Credit%20Card%20Information&amp;JSResize=reusableiFrameBody~height~parent.window%7CPageHeight%7C75%7C1000%5EreusableiFrameParentContentDiv~maxHeight~parent%7CreusableiFrameBodyParent~~parent+reusableiFrameBodyTitle~~parent%7C7%7C10&amp;AdditionalAction=1']</value>
      <webElementGuid>4f4b4877-3b01-46b3-b780-57c2adefec3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
