<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Previous Expiration Date_PriorExpirat_a5430d</name>
   <tag></tag>
   <elementGuidId>4405fe96-12f4-4cb2-86f0-4397d24cbf0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PriorExpirationDate_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PriorExpirationDate_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>162d55be-5bae-4f6e-aab4-54b9ca913f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec36b1c1-594e-4db0-8071-8f1d713d3b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateWidget form-control Both datepickerForDateWidgetPriorExpirationDate_1 TextboxOnly hasDatepicker</value>
      <webElementGuid>4d22ad8f-484b-4409-aa65-bf2759e1092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PriorExpirationDate_1</value>
      <webElementGuid>91a0904b-8252-4a61-93dc-48ad1a23a4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PriorExpirationDate_1</value>
      <webElementGuid>cbe8ad60-7e71-4c12-8151-8b98806197a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>5c6faee9-3f83-4f25-bd86-06490f254fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isDateJS(this);GlobalCalculated(this);  GlobalOnBlur();  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>d1a831db-d686-4763-8ae4-5e801696108c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskDate(this,event);</value>
      <webElementGuid>ad7be08b-0cbc-4cf2-aa6f-9c03dfa226e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PriorExpirationDate_1&quot;)</value>
      <webElementGuid>e982121b-a4fd-49e5-9cb5-586155663eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO3/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>ed4f313e-0193-4df6-abb0-d50e5caf70f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PriorExpirationDate_1']</value>
      <webElementGuid>9a7c0d0c-bc2b-49d7-9262-f4f4b7f0ed4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-PriorExpirationDate_1']/input</value>
      <webElementGuid>c8fbc99a-6c71-4204-a038-13a82cdbba30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>a9b0ca26-93f8-4756-ab64-fe6277503d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PriorExpirationDate_1' and @name = 'PriorExpirationDate_1' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>269bf119-7951-43bc-b57a-118b7fd60feb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
