<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEMultiPolicyDiscount_1</name>
   <tag></tag>
   <elementGuidId>97a61e73-4023-4397-bb98-cd1dea80694b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEMultiPolicyDiscount_1No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEMultiPolicyDiscount_1No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dfbf478-1be9-4341-9189-715e0f7c010e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b6df94c1-2efb-4f0f-9114-754b4545404e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ef961c5f-1835-4b63-b0e5-2c1e0ffbdfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd426426-893e-4fdf-bd1b-c3b12e2e7ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEMultiPolicyDiscount_1</value>
      <webElementGuid>7f5e4b5d-5e97-4cf2-a9f8-c8eb2a0b998e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEMultiPolicyDiscount_1No</value>
      <webElementGuid>bae686fc-5809-4e2d-bff0-c981582ada0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>e27b895c-1321-40b9-b1d8-411ed8580575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);  GlobalOnChange();  GlobalCheckDisable(this);</value>
      <webElementGuid>dec3d9e4-4cef-419e-bb00-a7dcdecdb715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>0197df3b-1061-4885-9e9e-fac42152365f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalOnBlur();  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>57c92107-93a2-459b-8d37-7a6db073ddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEMultiPolicyDiscount_1No&quot;)</value>
      <webElementGuid>6ec21313-28d7-4b83-b9a8-bb967f527eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO3/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>808cb077-a908-4526-acef-a61739673077</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEMultiPolicyDiscount_1No']</value>
      <webElementGuid>c7cbcfb6-9bfd-47a2-b794-8b652d2a79bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-MultiPolicyDiscount_1']/div[2]/input</value>
      <webElementGuid>d12358ee-f950-476c-b4cb-c59da7f8c002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[6]/div[2]/input</value>
      <webElementGuid>c39b4436-e834-4742-adcb-3de796e3e1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEMultiPolicyDiscount_1' and @id = 'NOSAVEMultiPolicyDiscount_1No']</value>
      <webElementGuid>3bdf03ea-9c6a-4cbb-8b80-a7349b63d0a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
