<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FEIN</name>
   <tag></tag>
   <elementGuidId>94eea9d6-b1aa-4578-89eb-003d01b20b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Wrapper-Left-FEINzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Wrapper-Left-FEINzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9af6f32-076a-4a3b-8099-6bbba6d23d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Wrapper-Left-FEINzzzz1</value>
      <webElementGuid>27f2b08c-be2d-4d10-8be7-bdd8963785e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 p-1    </value>
      <webElementGuid>be0961a6-f5a1-4bc1-a694-da70364ee8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FEIN </value>
      <webElementGuid>d82db71c-c8c0-48bd-b90c-6bafcaf6603c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Wrapper-Left-FEINzzzz1&quot;)</value>
      <webElementGuid>1426fd70-5028-400d-9f8a-fdac174aeadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>37719066-bb47-4f2f-9bd5-552a26027f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-FEINzzzz1']</value>
      <webElementGuid>08a7fc5e-ecc3-4c2e-ba04-e4f6e24412c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div/div[3]/div/div[2]/div[2]/div/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>a14b6449-5c2e-4b3f-88a8-3124101c49e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Information'])[1]/following::div[12]</value>
      <webElementGuid>7203e77b-533c-411a-8990-1bd1e8f49764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Address'])[1]/preceding::div[5]</value>
      <webElementGuid>2efe3d6a-4e2c-4e3c-a3b8-e06c31c99d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Address'])[2]/preceding::div[11]</value>
      <webElementGuid>65728adf-673b-4fe0-8ffc-3aa05ccbda17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FEIN']/parent::*</value>
      <webElementGuid>b2dcd313-a36a-4680-9217-ce8527cabb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>c85328df-7737-4711-b4ba-8b13eb3f8977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Wrapper-Left-FEINzzzz1' and (text() = 'FEIN ' or . = 'FEIN ')]</value>
      <webElementGuid>5e7d1389-fe7c-49b3-889b-0fa62d771108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
