<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Payroll_UninsuredTotalExposure</name>
   <tag></tag>
   <elementGuidId>cb624918-3c2b-444a-a40e-53993cc8ec3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UninsuredTotalExposure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UninsuredTotalExposure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57604884-b7bf-4208-856d-9fdff2fc45e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bc6fbcb-67ca-469f-9907-714ccc6698fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>0f82c1bf-fbc0-4608-a9d9-8be0358d884c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UninsuredTotalExposure</value>
      <webElementGuid>9e94e3b0-073b-49d4-9475-f3f966e5d81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7e1458a0-cabb-40bf-bbe2-7ee30ce5bd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71504020-70fe-4db2-8a42-e95b31dae144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UninsuredTotalExposure</value>
      <webElementGuid>d06b29c8-9c4e-4ccf-94b7-b300b01ccbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>15f711b8-e41f-49d4-a461-b224b7fa0f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this); </value>
      <webElementGuid>741eacef-f2df-4f3b-8052-d63ea049ddfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GlobalCalculated(this); </value>
      <webElementGuid>42a4d4c2-617e-44c1-b1d3-17fb30c206a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>3b29b7ac-ed5b-4af1-9d8e-025a56f266ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>2000000</value>
      <webElementGuid>c8e37383-5be7-4056-b019-41098208434e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d8bc4c90-8f83-4a54-ba34-244de18ced7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UninsuredTotalExposure&quot;)</value>
      <webElementGuid>e9da0a91-3d86-4907-ba18-06bed0985377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>b1b50695-3fe2-4d9b-a035-16db8a2663ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UninsuredTotalExposure']</value>
      <webElementGuid>39b344ca-62dc-4fbe-a6c5-79a83265ec35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-UninsuredTotalExposure']/div[2]/input</value>
      <webElementGuid>f7b80e3c-667b-4054-a969-63631014556f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>6a77e3bc-615a-4fe0-a489-d94efed0118a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'UninsuredTotalExposure' and @id = 'UninsuredTotalExposure']</value>
      <webElementGuid>09a862c7-c2f2-4cf2-8fba-cb9a6b2eef2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
