<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CGL 1002_NOSAVEBlanketInsured</name>
   <tag></tag>
   <elementGuidId>f2be9d0d-d4c9-4f33-ae10-c602f61c1cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEBlanketInsured']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEBlanketInsured</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c16c94c-92e2-4a38-a0df-4cd140170742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2185dc7f-8093-4399-8813-03bb7dbf4785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>35dc1ff7-4a37-4ede-bc23-43e865c77e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEBlanketInsured</value>
      <webElementGuid>ca954799-6adf-4974-833a-666b2915b770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEBlanketInsured</value>
      <webElementGuid>5aad0812-f76f-4df9-8cea-4d66c30f60eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UpdateCheckbox('BlanketInsured','Y','N');  GlobalCheckDisable(this);</value>
      <webElementGuid>ce6923cf-1bfa-405f-86e5-fe22884e6110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);</value>
      <webElementGuid>21f8a615-e417-41ee-b253-916d062c204c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEBlanketInsured&quot;)</value>
      <webElementGuid>37a8ab4c-6ded-496c-8ef3-1bce3291a96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>4180f513-aebd-4dd8-a06d-6a1813d5bad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEBlanketInsured']</value>
      <webElementGuid>71cc29e6-bda2-4473-9325-63be246ed8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-BlanketInsured']/input[2]</value>
      <webElementGuid>876aa4d1-e927-440c-ac6d-a902c0c35748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/input[2]</value>
      <webElementGuid>2c1e0bd1-9d42-4033-9f64-cf43b377fe81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'NOSAVEBlanketInsured' and @id = 'NOSAVEBlanketInsured']</value>
      <webElementGuid>0c264bff-0cce-4b00-be7f-315971dc949a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
