<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City, State, Zip, Zip4_ApplicantStatezzzz2</name>
   <tag></tag>
   <elementGuidId>82357f3f-0ce4-4b57-b853-ce9f5cb49658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StateCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='ApplicantStatezzzz2'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>209b27a7-f1b4-46ff-82b4-a1a0ce2f8ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StateCode</value>
      <webElementGuid>d1d97e5b-d39a-4b81-b898-948e3be79932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StateCode</value>
      <webElementGuid>c6d589f3-2c4b-49da-b6fb-29816f40da4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UpdateCompanyList(this.form,'StateCode');document.getElementById('ApplicantState').selectedIndex=this.selectedIndex;GMJSDataManager('0',document.getElementById('RealtimeGeocodingProviderSelector').value,'^ConstructionYear_1|');MakeVerifyStreetAddressCall('https://cypresstest.cogisi.com/is/',this.form,'Applicant','','',getMostRelevantPolicyTypeCodeValue(document.getElementById('PolicyTypeCode'),'',''),'0');;makeGetVeriskStatusJSCall();</value>
      <webElementGuid>7761e087-f932-4b7e-84ea-986064f94848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FLORIDATEXAS</value>
      <webElementGuid>51793ebc-2fc6-4ecc-81c2-de8b719eb176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StateCode&quot;)</value>
      <webElementGuid>a23245d2-9f6a-4972-8053-c0c521c2c5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>30240fd8-ab87-4d3c-81fc-b3a0fb247dd9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
