<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prior Expiration Date_PriorExpirationDate</name>
   <tag></tag>
   <elementGuidId>de573fcc-42a4-4bab-ac23-fe9a386db28b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PriorExpirationDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PriorExpirationDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5624716-0e36-4c6a-a6f1-b9a3cfa9ec06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3e7bac0-bcdf-4f28-8127-ed25e1ee458d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateWidget form-control both datepickerForDateWidgetPriorExpirationDate TextboxOnly hasDatepicker</value>
      <webElementGuid>bc32169e-1d4e-4784-b0b1-45fec8076518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PriorExpirationDate</value>
      <webElementGuid>9e9f0c7e-60b9-40f2-a1bd-ee08d79debab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PriorExpirationDate</value>
      <webElementGuid>b5ded63f-7351-4c9f-9b53-2400c04c0cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>fc472fba-db5b-4898-b452-124f639349fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isDateJS(this);   CheckRequired(false);</value>
      <webElementGuid>d276e256-5a30-459e-a290-259578dc759f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskDate(this,event);</value>
      <webElementGuid>e4a1edfa-3f99-4ef0-b66f-e53eb6ab4264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PriorExpirationDate&quot;)</value>
      <webElementGuid>2915122b-013c-4e09-9357-a42fbf4ee66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>46841f91-25eb-4d79-9295-73bbf2cdf59a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PriorExpirationDate']</value>
      <webElementGuid>9faaa64b-edd4-45af-820a-7eff8c76face</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-PriorExpirationDate']/input</value>
      <webElementGuid>711dd1a5-ed10-4393-aadb-30a6a979e65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>4a741ad1-e26b-470a-aabe-d8256b99adac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PriorExpirationDate' and @name = 'PriorExpirationDate' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>1a041b5b-eb0b-4a31-a45a-2e04af8e243b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
