<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City, State, Zip, Zip4_ApplicantCityzzzz2</name>
   <tag></tag>
   <elementGuidId>d1cc1ec3-ad12-4ca0-a2a2-1e711a6749ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantCityzzzz2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantCityzzzz2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcd2ef73-b7bd-4ce2-8422-22b93100433d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a17ceb0-57bf-4f43-9ed9-ad907142e14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7397ab85-1057-425e-bcc9-32dd27b1e28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City*</value>
      <webElementGuid>0bbf6620-f4f3-4fe1-ae32-7449a115a63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f5aa8f19-d558-432c-b14d-2490f579c77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantCityzzzz2</value>
      <webElementGuid>0a4fa2e5-6e17-4ee4-bc31-d7398152a1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantCityzzzz2</value>
      <webElementGuid>6c57ed4d-7a2a-487e-9a0c-df7796682d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);USPSRealtimeAddressValidation('a37738514545518838i41158914s3052680142490431i72171','https://cypresstest.cogisi.com/is/','3010030','Applicant','zzzz2','City',0,0);</value>
      <webElementGuid>a07a7ad7-c574-4e05-99d7-f58701ce9f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Applicantzzzz2').value='0';</value>
      <webElementGuid>57f764b9-db9d-4914-9675-8d7fb7982d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>580e2244-6126-4bb2-9985-b50fff7c18bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantCityzzzz2&quot;)</value>
      <webElementGuid>c1ea777a-87e0-4c2b-b0d6-0eca7be078d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>41c65aaa-bc8e-451b-a6a5-bd279f8f0341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantCityzzzz2']</value>
      <webElementGuid>426a10b9-6635-433f-b3c7-b26826b346f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantCityzzzz2']/div/input</value>
      <webElementGuid>095e16f6-df8f-496f-909c-ba84a48d30e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>354b46b4-4b4c-4d5d-9c9c-c49c2e31e4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'City*' and @name = 'ApplicantCityzzzz2' and @id = 'ApplicantCityzzzz2']</value>
      <webElementGuid>a21c37cf-171f-4bee-90ae-1080fe256884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
