<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NumberOfPeople</name>
   <tag></tag>
   <elementGuidId>1a62a229-d73c-4bcc-9d3b-d7af2e18bc78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GrossReceipts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActiveOwnerNumberOfPeople']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca4f7abc-780b-4e1e-bd8a-1389b8ade543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff30116d-778b-4800-b134-6e176bc5cc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget </value>
      <webElementGuid>a9480368-8a14-42ce-b8c0-242a396bd0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GrossReceipts</value>
      <webElementGuid>7b9e5c80-b90c-415d-937d-61ad07b807be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>70a04cba-8129-4bdb-889d-bbe6d9d6b038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabletohide</name>
      <type>Main</type>
      <value>DisableElement_GrossReceipts</value>
      <webElementGuid>062f97c1-c46f-4136-a660-29680b3780d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GrossReceipts</value>
      <webElementGuid>1cec5920-7241-40a9-84f3-bcda53006036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);   CheckRequired(false);</value>
      <webElementGuid>d8eca3d6-3252-4c96-85d6-3adae0fc368b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>d8842ae1-e55d-42ea-9de5-26e5bc716f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>4000000.00</value>
      <webElementGuid>57483ab5-33b4-4b7a-8b42-c462896758e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>16700.00</value>
      <webElementGuid>257334f9-2423-42b9-8396-f1b3fa69b6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5571a002-a1d8-4ccd-9d0e-f04c359b3855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GrossReceipts&quot;)</value>
      <webElementGuid>7339033e-29b0-487b-bcc7-48aebda5d639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>76fc8ad2-14fb-41d2-8c2f-ac0a7dfeef7b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
