<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CurrentLicenseNumber</name>
   <tag></tag>
   <elementGuidId>4904990b-e4cd-45eb-82a4-83c9fe2e0236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LicenseNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GrossReceipts</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc89b901-8438-49b2-bffb-9874f27f5a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f9d1f25-533a-4c82-b782-6b5058b10641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget </value>
      <webElementGuid>38a0c969-f53f-4015-b009-70cc47cf40c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GrossReceipts</value>
      <webElementGuid>96dc8be3-988f-4ba4-9188-b256ff9c59db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6328fe6b-2aef-4cd1-bc17-e29278816990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabletohide</name>
      <type>Main</type>
      <value>DisableElement_GrossReceipts</value>
      <webElementGuid>4825c8c7-95a6-4a39-829d-3a9e47ec2438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GrossReceipts</value>
      <webElementGuid>abaa8805-7146-47c8-b2f4-e695e6a3b47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);   CheckRequired(false);</value>
      <webElementGuid>5f365868-63de-41d7-b9ab-79d8a64f4dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>45f3f3d0-fbe0-4e66-b2e7-e1affdacd7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>4000000.00</value>
      <webElementGuid>290bf298-c872-4c74-9794-9edf7f538e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>16700.00</value>
      <webElementGuid>17f3b214-710f-4da9-aba7-21f90374736f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c87936b2-2c27-4d31-886b-49feb263b34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GrossReceipts&quot;)</value>
      <webElementGuid>948b6623-40da-4ad5-8675-12096c20f2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>392372dc-cb80-44b3-816a-3765f411471d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
