<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Prior12MonthsSubcontractCosts</name>
   <tag></tag>
   <elementGuidId>77cc417d-2e3c-42a3-8d05-4f10c09e7315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Prior12MonthsSubcontractCosts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Prior12MonthsSubcontractCosts']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a501c29-1aeb-4a5c-96be-f20cc0ead439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4c8bcff-72e5-41df-a932-a0f3aecd2918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget </value>
      <webElementGuid>5c6b2b50-1c75-4b5d-a64b-c53c1a79aaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Prior12MonthsSubcontractCosts</value>
      <webElementGuid>a2c01dd4-2db1-474e-9a2c-471d872b2d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>e2b8c35f-4918-462f-b75b-721abe325f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ec0add7-291b-4ec1-8f4d-671473bae55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabletohide</name>
      <type>Main</type>
      <value>DisableElement_Prior12MonthsSubcontractCosts</value>
      <webElementGuid>f493abe4-218c-4137-9bb7-16c32c642688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Prior12MonthsSubcontractCosts</value>
      <webElementGuid>11562a00-6aa8-4955-84f4-cecf153f2b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>e5896a8d-21e6-44fb-a962-935558faefda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>e8a2ae76-d07f-4392-8f70-6a8dde892a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>  GlobalCheckDisable(this);</value>
      <webElementGuid>ced83a32-a3fb-4a82-88fd-03d65067508e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>02049274-7d9c-4ed6-b747-6d0dd8c60109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>eaf83417-2356-42dd-a694-55e84471aeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6b351d45-0c52-4887-8650-fcbb7dd30dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Prior12MonthsSubcontractCosts&quot;)</value>
      <webElementGuid>b32ec4a7-08ec-403c-a186-b0fbab49f303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>d5559635-5f03-4038-a0fc-2fec8c7b3a44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Prior12MonthsSubcontractCosts']</value>
      <webElementGuid>42fe077a-ad1e-4ca0-9348-f0c51a85107a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-Prior12MonthsSubcontractCosts']/div/input</value>
      <webElementGuid>513e8833-956d-4be9-bc46-f49eba652054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div[4]/div/input</value>
      <webElementGuid>b5f3ce31-6b7c-43dc-9a0a-90774d58a156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Prior12MonthsSubcontractCosts' and @id = 'Prior12MonthsSubcontractCosts']</value>
      <webElementGuid>d73d7d25-4441-42bb-9eea-75e6aefea8d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
