<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Insured, , s Email)_ApplicantE_08aac7</name>
   <tag></tag>
   <elementGuidId>d2800341-5b79-4e8d-a1f8-ae4cce4c885e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantEmailzzzz1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ApplicantEmailzzzz1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1472daa3-d92b-4d85-8d5d-be7b2f70d959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16b0f0f5-8f6a-409f-8fd7-c15b30e8c0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>15992aee-b826-4939-bf5a-a135114247b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>18423cd7-24a5-4fc0-b13b-5fe9c32d1068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>bdb728f3-0453-4e94-95de-93dc1993a928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckEmail(this);  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>a0be42ce-4a90-4ef6-94a4-9269e6a78649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantEmailzzzz1&quot;)</value>
      <webElementGuid>67bcb6be-2d1a-42bb-86dc-f4ea7d18cc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>d97885be-057a-4cd6-945f-10c129bcb87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantEmailzzzz1']</value>
      <webElementGuid>c1e90210-9dd5-42cf-939c-76a48319020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ApplicantEmailzzzz1']/input</value>
      <webElementGuid>3d066407-245a-463c-83d2-636bc096caea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>74cbb522-531c-4660-be4f-203357b23b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantEmailzzzz1' and @id = 'ApplicantEmailzzzz1']</value>
      <webElementGuid>6652ec0a-4b30-4636-92c7-7d2ed9839f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
