<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of People_ActiveOwnerNumberOfPeople</name>
   <tag></tag>
   <elementGuidId>23c5de89-0459-4fc5-941f-b9309847c212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ActiveOwnerNumberOfPeople</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ActiveOwnerNumberOfPeople']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dcc39bf-21b6-40f0-a274-e72d9a1f24ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84aa1619-03eb-4d9b-bad3-5679e8ee4f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>4a08d328-7070-43d8-a3e3-e3b821d5d62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ActiveOwnerNumberOfPeople</value>
      <webElementGuid>845e2c0c-2d26-4be1-b61f-769161b0f3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fe0479f7-b95c-4a53-b1f6-a77e94052750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1bf65998-f820-41f4-bf27-4f4fd2279c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ActiveOwnerNumberOfPeople</value>
      <webElementGuid>5d91256f-3c44-45e1-9b80-041f3dafd1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6c3f2f6f-6f96-4aec-a6f4-ed6fcda7395a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);   CheckRequired(false);</value>
      <webElementGuid>bee2eb1a-52de-4281-a66d-e232b859a9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GlobalCalculated(this); </value>
      <webElementGuid>d795872b-02fc-48f0-92b6-3278aa320bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>b5655a1c-d4bd-4fe0-be6f-366a98869cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>51f4b7ea-b294-4d3a-897d-a453ec238f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6d1d9e0-cc99-4b30-9fc2-7e6274b03bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ActiveOwnerNumberOfPeople&quot;)</value>
      <webElementGuid>3ce5a4ac-481e-46d0-af1b-e3435f5a9930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>3a3a92f8-0405-42ea-94ba-be1c5f19474e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ActiveOwnerNumberOfPeople']</value>
      <webElementGuid>d37a1b02-5041-4a0f-be01-8484a434ee77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ActiveOwnerNumberOfPeople']/div[2]/input</value>
      <webElementGuid>a4f1a5a4-9301-424b-98a6-f718356f5956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>0d803973-a256-4251-ad2e-c5de22581eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ActiveOwnerNumberOfPeople' and @id = 'ActiveOwnerNumberOfPeople']</value>
      <webElementGuid>9d771b0b-fd12-492e-a40c-aa1fc3e2309c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
