<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVESalvage</name>
   <tag></tag>
   <elementGuidId>c37be377-4d04-40a8-a4d1-fa363f0e36b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEEngagedinSalvageNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEDoesRoadsNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40477134-08e2-401b-9844-f058ade8fca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a3925f5a-a901-43a3-8b59-dbbbed03dc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f656f3ae-500d-47fb-a055-6cdea0554d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57e7600f-5286-4f37-b64c-495055c5d829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEDoesRoads</value>
      <webElementGuid>8daf1391-8b7e-46fc-947c-c5c740f89a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEDoesRoadsNo</value>
      <webElementGuid>69e919a1-7ad0-41c2-abac-7df38039deef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>03eebec5-b27a-4c7c-888d-26556fa3a9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);setIfPresent(this,'DoesRoadsRemarks','','input');  GlobalCheckDisable(this);</value>
      <webElementGuid>27b6a199-36f2-4173-8301-17817a993e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>ce922767-3670-40b1-a767-57d7619118d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>81f4845c-93b6-4054-bd00-6fea8c9bfe66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEDoesRoadsNo&quot;)</value>
      <webElementGuid>c287266f-5663-4c02-99e4-fd8d9619b9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>a9ef5034-4d52-4b71-a587-15d243abde52</webElementGuid>
   </webElementProperties>
</WebElementEntity>
