<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of People_FullTimeNumberOfPeople</name>
   <tag></tag>
   <elementGuidId>166d54fc-7683-4397-af23-1ba551ab7354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FullTimeNumberOfPeople</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FullTimeNumberOfPeople']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>853e1021-e4d7-42cb-98a9-bc1d7e97adff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d586a16-ae29-43b6-8dec-dbc93bf3179a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>7c7303c2-cf4f-4731-a8e3-6b382c61f8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FullTimeNumberOfPeople</value>
      <webElementGuid>4ba88a35-9689-4120-98d1-35a9186e1a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24d38eea-fc6f-4a09-9382-5dee8dcacef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66809a17-f7c3-48e8-b6eb-500208779de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FullTimeNumberOfPeople</value>
      <webElementGuid>c13e0048-5a6f-46ac-a588-d74bea10f36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef55ff93-5eb7-4119-96f3-4968be773a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this); </value>
      <webElementGuid>37b8b3e5-5235-4902-a141-ad72af44ff7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GlobalCalculated(this); </value>
      <webElementGuid>6ac3cb0d-ded1-4d52-bc2a-57e8cf8ea2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>03fb4f34-0987-44f6-b1b0-9000abf7784e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09363bb9-9604-4715-892b-c2769845e43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FullTimeNumberOfPeople&quot;)</value>
      <webElementGuid>e5d7a7a1-816c-4077-afc1-e1c8a891d33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>d439f036-3b3e-4bd3-b007-fd316dfaccef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FullTimeNumberOfPeople']</value>
      <webElementGuid>7047001e-dd83-4367-b296-1d4bcf67ce9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-FullTimeNumberOfPeople']/div[2]/input</value>
      <webElementGuid>af92c4f6-549b-48fd-9aa6-9b12fc539913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>73593255-3da2-465c-a692-829acfb506ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'FullTimeNumberOfPeople' and @id = 'FullTimeNumberOfPeople']</value>
      <webElementGuid>bee29347-6a22-4bae-b64e-ee817440da8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
