<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CIM CPC 805_NOSAVEToolCoverage</name>
   <tag></tag>
   <elementGuidId>78333242-8bbc-4a68-afc4-35552d7870e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEToolCoverage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEToolCoverage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e222d950-11ab-4e87-a26b-77ed5675a929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3ad1023-42b4-4775-8228-1c17d3a5fa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>05d846a4-67c1-4f7c-b782-c38b8d87fb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEToolCoverage</value>
      <webElementGuid>31769edb-abde-4aa5-a715-34a04439d805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEToolCoverage</value>
      <webElementGuid>01e1fe99-dc7d-4a15-a118-0a94d42847f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UpdateCheckbox('ToolCoverage','Y','N');  GlobalCheckDisable(this);</value>
      <webElementGuid>bda7cae0-37dc-4ecd-9649-4575783f2c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);</value>
      <webElementGuid>58801260-2d54-441c-bde5-7e303e3fea37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEToolCoverage&quot;)</value>
      <webElementGuid>45758413-bc31-4576-9c9b-72b3652b2a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>9a861af9-c46d-4fb9-99f7-8ec7f38b97ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEToolCoverage']</value>
      <webElementGuid>489478cb-13cb-41c9-bd40-814fc8e72964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ToolCoverage']/input[2]</value>
      <webElementGuid>0a8a57c2-1b0e-423f-8ba1-ac7e461dfb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div[2]/input[2]</value>
      <webElementGuid>132717c8-4dd7-4f6c-8fee-ede76cae13a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'NOSAVEToolCoverage' and @id = 'NOSAVEToolCoverage']</value>
      <webElementGuid>9128c388-ffd8-4c08-ac83-7df0b7d5d5f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
