<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEPriorCypress</name>
   <tag></tag>
   <elementGuidId>92e49681-3039-4be9-b37b-881bf1f1f8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEPriorCypressNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEPriorCypressNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f5d8b3a-d85b-4b9b-86ed-1edb304ca4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4600ad7f-1a1c-47b0-b9a8-65962c6ea6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4c18ef75-4e26-4616-83e5-9950f40c0312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>56d486a3-8096-40ec-85cb-59fc8c0a2d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEPriorCypress</value>
      <webElementGuid>339fc1ef-3c65-4ed1-a52a-1d11df8d2184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEPriorCypressNo</value>
      <webElementGuid>37d1fb2f-76b4-44df-a0fc-0a162d284f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>ca78003f-2ce8-435c-be47-a49397cec390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);setIfPresent(this,'PriorCypressRemarks','','input');  GlobalCheckDisable(this);</value>
      <webElementGuid>2c92b85c-65b0-4243-af16-512b12fdf494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>83271811-1387-4525-98f2-74ec3028244b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>47254997-e432-4ded-a94d-c2cde6b5b176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEPriorCypressNo&quot;)</value>
      <webElementGuid>c4b166b1-48e3-414e-b31b-ba1230603d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>ac86984a-afef-4e2b-b24d-df01b445ce3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEPriorCypressNo']</value>
      <webElementGuid>8429929c-196c-46f5-a9d3-69518e7435ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-PriorCypress']/div[2]/input</value>
      <webElementGuid>e6ef9459-1e07-42df-84cc-ee0f80574c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/div[2]/input</value>
      <webElementGuid>5ac65afb-5ea2-43cc-9b4e-c8ab3d9269b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEPriorCypress' and @id = 'NOSAVEPriorCypressNo']</value>
      <webElementGuid>ac5cdbfd-b5d6-433a-89ad-e3b3c518bbe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
