<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FLORIDATEXAS</name>
   <tag></tag>
   <elementGuidId>75d885c6-d3c4-4e16-84dd-bf576520b1dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StateCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StateCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7138c76-2203-41ae-9cd7-96069a101110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StateCode</value>
      <webElementGuid>b293f163-1459-4b74-a783-bbba3a7e8d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StateCode</value>
      <webElementGuid>9cd65ebd-b29e-4737-a2e6-95b1c3fa1d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UpdateCompanyList(this.form,'StateCode');document.getElementById('ApplicantState').selectedIndex=this.selectedIndex;GMJSDataManager('0',document.getElementById('RealtimeGeocodingProviderSelector').value,'^ConstructionYear_1|');MakeVerifyStreetAddressCall('https://cypresstest.cogisi.com/is/',this.form,'Applicant','','',getMostRelevantPolicyTypeCodeValue(document.getElementById('PolicyTypeCode'),'',''),'0');;makeGetVeriskStatusJSCall();</value>
      <webElementGuid>9dcc6226-0d7e-475c-80b4-ecb3724185f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FLORIDATEXAS</value>
      <webElementGuid>e15938aa-4423-40a5-8e0b-3d9ae4b7a75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StateCode&quot;)</value>
      <webElementGuid>8bd33deb-2e5e-41f4-84ba-bf5fa7cf950a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>64fe4f11-a385-45b6-8d08-71f2f29bc73d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StateCode']</value>
      <webElementGuid>bd6045bc-7738-475b-ab41-c6856fbf6f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='StartANewQuoteFormTable']/tbody/tr[2]/td[2]/select[2]</value>
      <webElementGuid>8aa798b2-1e98-4c8e-a9ea-bce1e740e084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State:'])[1]/following::select[2]</value>
      <webElementGuid>52281b8a-b309-42fe-ba54-74de5ec9c657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Type:'])[1]/preceding::select[1]</value>
      <webElementGuid>d6c0ed4b-c1ca-4fda-85e1-cc5f8b1010e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>088a9f12-6155-43c7-99a9-3d0efb6912cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StateCode' and @name = 'StateCode' and (text() = 'FLORIDATEXAS' or . = 'FLORIDATEXAS')]</value>
      <webElementGuid>14af5403-d395-4824-96ea-cae41513e1c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
