<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_TEST AGENCY</name>
   <tag></tag>
   <elementGuidId>9856f092-80b3-4538-a89f-e8c366f6a1b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.sorting_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='displayAgentsTableAgentCode']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7c6f81c0-c4c2-4534-91d8-32c2dce0c68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>b6df2fac-8995-4351-8bb0-ec7709857497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST AGENCY</value>
      <webElementGuid>f642feee-6f2e-44f1-b3de-693b58e8381e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayAgentsTableAgentCode&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>c5c2a784-1f95-4dc0-8bb7-27c71e241b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>c1e7a9d9-8770-4d14-8d6d-fedf3ff58008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='displayAgentsTableAgentCode']/tbody/tr/td</value>
      <webElementGuid>dd45acfe-5e6f-42f2-87b0-4fe27d99617c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent ID'])[1]/following::td[1]</value>
      <webElementGuid>bfe8ea0f-1bb1-4aa5-8ff4-b3b962db2c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent Name'])[1]/following::td[1]</value>
      <webElementGuid>ad27aabe-b716-4f52-a718-2d88a8cce963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries'])[1]/preceding::td[2]</value>
      <webElementGuid>dc203b04-a3aa-404a-a88c-6a0164bdcd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::td[2]</value>
      <webElementGuid>d9a87d4e-9ec0-4b80-81c5-48eff6ef39a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEST AGENCY']/parent::*</value>
      <webElementGuid>24c4d6b2-b7de-4073-9f2a-0d3ee04830b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>4204122d-3a3e-4050-b3dd-ac9bcb74577c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'TEST AGENCY' or . = 'TEST AGENCY')]</value>
      <webElementGuid>ce5524a7-8694-450c-95aa-c2d503091bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
