<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_ApplicantAddress1</name>
   <tag></tag>
   <elementGuidId>97b69171-3179-4334-918a-74ce88f4ea7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantAddress1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantAddress1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cb7b631-75b0-49aa-a83b-f03cba5d2830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7ae2029-e433-4f77-b007-76597f7ebdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae031ca4-8f75-4060-850b-a01d3fd58f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address1*</value>
      <webElementGuid>591600b3-3657-417d-a2f4-0032175852a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a32781ca-2318-4a59-bad6-d1de9eb633b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantAddress1</value>
      <webElementGuid>b7ee94cb-a0a4-4a27-b2f4-4334df2dc7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantAddress1</value>
      <webElementGuid>4fbb3e51-cca9-43c1-b1de-7af7f6662db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);USPSRealtimeAddressValidation('a64706586571534616i38932015s4952440192948260i67440','https://buildersrisktest.cogisi.com/is/','300150','Applicant','','Address1',0,0);checkForUpperCase(this);</value>
      <webElementGuid>419cf2a7-c875-4028-9110-36c26994375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Applicant').value='0';</value>
      <webElementGuid>062fdd73-d5d3-40c7-ae63-fc7c757d6b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>82dd5900-13dd-4019-b4b3-b75a7ff441a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantAddress1&quot;)</value>
      <webElementGuid>06136224-ea01-47df-a350-edf338c1d69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>30dd54a3-03ed-4b49-9f36-035bee453d52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantAddress1']</value>
      <webElementGuid>1a3cefcd-ac3d-49ae-8e17-7e51bca47d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantAddress1']/div/input[3]</value>
      <webElementGuid>36218185-e9b1-4530-b610-67509ff7f83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[3]</value>
      <webElementGuid>668a5c5b-1612-4e2e-8d00-9f9a736517a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Address1*' and @name = 'ApplicantAddress1' and @id = 'ApplicantAddress1']</value>
      <webElementGuid>bcf9647e-921d-4f26-ac7f-b22fb020fa41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
