<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location Address_ApplicantAddress1</name>
   <tag></tag>
   <elementGuidId>3e5496d5-85b2-4c17-bae2-46abc0bfd179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantAddress1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantAddress1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f78a4bf-3287-4bac-b81c-e3b00aa7b8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3bd63ef9-978e-474e-930f-d6ec7e71ead5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantAddress1</value>
      <webElementGuid>c4562b95-53d1-469f-863c-f192bd3d6530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantAddress1</value>
      <webElementGuid>99cc731c-9d1b-4eb7-9f96-bd9311ab07ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>1baa814d-7044-48ae-b677-e2adfd2aca2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>72bf3596-d67a-42c1-a66c-3e015b22d4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GMJSDataManager('0',document.getElementById('RealtimeGeocodingProviderSelector').value,'^ConstructionYear_1|');MakeVerifyStreetAddressCall('https://buildersrisktest.cogisi.com/is/',this.form,'Applicant','','',getMostRelevantPolicyTypeCodeValue(document.getElementById('PolicyTypeCode'),'',''),'0'); </value>
      <webElementGuid>8cd24988-23e4-4f1c-a94e-b87c02a4166e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>; chkQuotes(this); UpperCase(this) </value>
      <webElementGuid>9245ec23-7038-447b-91ec-eb18fcd33d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantAddress1&quot;)</value>
      <webElementGuid>25cf5901-a292-4fe6-8b30-93e7269df59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>b4c8861a-96b1-47fe-9437-2cdb56135ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantAddress1']</value>
      <webElementGuid>793aa94e-20df-4eda-ad9d-f55687b44028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='QuoteAddress1']/td[2]/input</value>
      <webElementGuid>1050f5a8-80bf-49fc-a98d-f5381ef4f4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>e3080dd4-a481-4155-931c-ac5d1399d0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantAddress1' and @id = 'ApplicantAddress1']</value>
      <webElementGuid>31832f9c-aeac-4ea8-b79c-3a3d869c2b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
