<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please choose a name type_NOSAVEAppli_f4d688</name>
   <tag></tag>
   <elementGuidId>886b947f-35d4-4bf8-8e28-62e6d77979fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEApplicantAskzzzz1I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEApplicantAskzzzz1I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b768d83e-7a27-460c-b3f9-c8ed87086915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c9f68d76-e501-4058-9797-28de33b5cffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1f58a49e-76f8-4926-9489-14b77f9b171c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEApplicantAskzzzz1</value>
      <webElementGuid>0e986d96-a689-44a5-a86a-f47b9deafff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEApplicantAskzzzz1I</value>
      <webElementGuid>1d687a53-7658-451e-a3d2-f3b25676db3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I</value>
      <webElementGuid>6b6ad326-13c3-446f-a392-91433482f70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);handleNameAsk(this); GlobalCheckDisable(this);</value>
      <webElementGuid>b3dff768-d14c-4859-8f6d-bb67ac4fe4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);</value>
      <webElementGuid>b084b586-e02f-4d49-9ebb-53ab4e19d9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEApplicantAskzzzz1I&quot;)</value>
      <webElementGuid>40a6f8c2-d5ee-4da5-a658-1b31d5c25ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>3dba6d12-c035-426b-9b9e-78f29b578ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEApplicantAskzzzz1I']</value>
      <webElementGuid>32301194-896e-4f2d-97ad-761abbde4c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-Applicantzzzz1']/div[3]/input</value>
      <webElementGuid>506ef9ce-afda-4da1-8732-6f903972945a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input</value>
      <webElementGuid>096ba7ee-2b7d-40cb-88f9-3bee4eff92b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEApplicantAskzzzz1' and @id = 'NOSAVEApplicantAskzzzz1I']</value>
      <webElementGuid>fec0b20e-05dd-44ce-9e0b-5fde1a2cf08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
