<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applicant Suffix_NOSAVE-INDApplicantS_d9ac27</name>
   <tag></tag>
   <elementGuidId>b7eac651-55ff-4d19-8947-df406068abcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantSuffixzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantSuffixzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f02cab0e-0fbe-48c5-9b66-93bcb2ee8878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43752613-e973-44b8-a303-7e8a1aa30ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkForUpperCase(this);processAskLastName(this,'ApplicantSuffixzzzz1');</value>
      <webElementGuid>7b9a9789-b74f-4eb1-9c47-1e50299c6555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ISiA-Force-Uppercase</value>
      <webElementGuid>43cf9e43-5f77-44fe-83f8-2b9f67c4681e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Suffix</value>
      <webElementGuid>c9cc3c0b-c61e-458a-a201-834b3b19ef41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVE-INDApplicantSuffixzzzz1</value>
      <webElementGuid>7ecc30dc-6dc5-4eb4-b69b-3cd4f2792f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantSuffixzzzz1</value>
      <webElementGuid>7a7fa42d-8717-4cf8-9cd6-8db0add7b99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>456ae14e-0318-428e-b088-5e5e14207aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantSuffixzzzz1&quot;)</value>
      <webElementGuid>bf04fe24-da4b-4d5e-bb36-19ac5b35e092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>51839707-9c35-41ad-99a0-4fa9afcf91b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantSuffixzzzz1']</value>
      <webElementGuid>32c05148-87ca-4ca0-89ce-89b8c7cf2c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantSuffixzzzz1']/input</value>
      <webElementGuid>0d7296ca-8874-4f4f-ab3d-2c17cf8bdfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/input</value>
      <webElementGuid>91832f16-23ca-4858-a92c-2d3c841f480f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Suffix' and @name = 'NOSAVE-INDApplicantSuffixzzzz1' and @id = 'ApplicantSuffixzzzz1']</value>
      <webElementGuid>bfa8deb6-0c91-431f-883c-4d79d7d9dfb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
