<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_EffectiveDate</name>
   <tag></tag>
   <elementGuidId>c829c0a1-4c59-45e1-96e5-f60a8880f2f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EffectiveDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EffectiveDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6aa9b450-724a-4ea6-8ad6-61664dd8045c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f447ee51-1d1a-4996-a28d-3951f2e89e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EffectiveDate</value>
      <webElementGuid>d696858c-6969-49ac-8f08-241f20004c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>effectiveDateOnBlur(this)</value>
      <webElementGuid>00f57b17-78da-4571-b51f-4e6450e58621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EffectiveDate</value>
      <webElementGuid>1ea5a4e0-7f8f-4143-9634-46d4c4a06b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0a79297d-366b-49ad-94b4-239228bded18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08/07/2024</value>
      <webElementGuid>2c421d1e-23ee-4916-b7d1-e968e5bf0a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskDate(this)</value>
      <webElementGuid>b2fd369a-658f-4099-97c7-a8213c3aa078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>22d3ea0e-e2a1-46cc-8e2a-ec990ed79d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hasDatepicker</value>
      <webElementGuid>d8a4b317-3e13-4a38-bfa3-ca716c0d7321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EffectiveDate&quot;)</value>
      <webElementGuid>93c10224-4fa5-41f0-9237-31133bca9f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>e3e7fefa-4c05-4abe-9b7c-2bd2816e13ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EffectiveDate']</value>
      <webElementGuid>d2f095f1-3f00-4c2d-b7c4-13722cd761db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='StartANewQuoteFormTable']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>f9976e75-0ba1-4d88-8a73-7c7a183fe9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>e23346dd-dd50-4cce-b2de-ac7410a1b2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'EffectiveDate' and @name = 'EffectiveDate' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>ca0ee77d-13b2-422c-8cc7-c0def6cb9282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
