<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_updatesElectric</name>
   <tag></tag>
   <elementGuidId>52d8c6a9-17f6-49cf-a6b8-45fce18fb74f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ElectricalYear_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ApplicantZip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edfd55da-f634-4e44-bc32-504f29da49b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18abd48f-fb58-4191-95d1-4e3c183d520f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantZip</value>
      <webElementGuid>d4dc9150-6c80-4837-9ab3-c9526ad1ca10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantZip</value>
      <webElementGuid>cabe978d-f868-402c-9eb0-76065cce1c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>32f5157f-014a-4d1d-b67d-33b2c2ed9be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>af891e24-3503-4879-a5b1-1fc47ef7f176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GMJSDataManager('0',document.getElementById('RealtimeGeocodingProviderSelector').value,'^ConstructionYear_1|');MakeVerifyStreetAddressCall('https://buildersrisktest.cogisi.com/is/',this.form,'Applicant','','',getMostRelevantPolicyTypeCodeValue(document.getElementById('PolicyTypeCode'),'',''),'0'); </value>
      <webElementGuid>e0549136-238f-45ba-8dc2-767ce0cfcf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>; chkZip(this) </value>
      <webElementGuid>52e11d8b-d2d7-4f7c-b4d9-19f76b1058bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#####</value>
      <webElementGuid>1c6234ff-aab9-428a-acaa-c8b37722a7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantZip&quot;)</value>
      <webElementGuid>ca57fb28-ef2e-4655-b39b-c28ba5c70494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>042c0ec9-9929-484b-ad72-5c8402b05919</webElementGuid>
   </webElementProperties>
</WebElementEntity>
