<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>policyID</name>
   <tag></tag>
   <elementGuidId>025a96a7-01e2-4924-8780-aec805fda96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ExpandedHeader.ISiPolicyHeader > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='extended_header']/td/table/tbody/tr/td/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>6fffb1b9-dc2b-4d3e-b861-b4f83b803f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account ID: 3748</value>
      <webElementGuid>6288d580-7024-4208-b6f3-cfc478ccb3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicyDetailsMainDiv&quot;)/div[@class=&quot;ISiWhiteCanvasHeader&quot;]/table[@id=&quot;acct_header_table&quot;]/tbody[1]/tr[@id=&quot;extended_header&quot;]/td[1]/table[@class=&quot;ExpandedHeader ISiRowHighlighting&quot;]/tbody[1]/tr[1]/td[@class=&quot;ExpandedHeader ISiPolicyHeader&quot;]/b[1]</value>
      <webElementGuid>1e565546-c0e7-4619-a0a1-5bd4e88ca75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>fedb0987-12ab-454c-a2d7-2854ede4efbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='extended_header']/td/table/tbody/tr/td/b</value>
      <webElementGuid>27eb8229-ba44-4fc2-9299-d27028de98f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='agentemail@cornerops.com'])[1]/following::b[1]</value>
      <webElementGuid>927ddd44-6b69-4c0b-9e96-f919e93b3253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current:'])[1]/preceding::b[1]</value>
      <webElementGuid>3e2b256c-0613-40ed-a422-f41c77c2ec6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3748']/parent::*</value>
      <webElementGuid>48f87a55-fb22-4d3a-9947-dcb19eb6c27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/b</value>
      <webElementGuid>3fbb9c60-fe7f-4cc1-afea-f8631ef80e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Account ID: 3748' or . = 'Account ID: 3748')]</value>
      <webElementGuid>b0406fd6-52e1-4e31-b620-659dfa206e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
