<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue_mat-mdc-button-touch-target</name>
   <tag></tag>
   <elementGuidId>34aa9c6b-b7a7-47b7-8c6e-79e24e1a4086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iv360-continue > span.mat-mdc-button-touch-target</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='iv360-continue']/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8036b0b-fc92-4dab-b81f-51e0df301e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-button-touch-target</value>
      <webElementGuid>52a0c908-a371-4be8-997a-6171e2fe26f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iv360-continue&quot;)/span[@class=&quot;mat-mdc-button-touch-target&quot;]</value>
      <webElementGuid>54df3f95-37af-4e47-bcfe-e63038e621f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='iv360-continue']/span[4]</value>
      <webElementGuid>12680579-cb6c-4115-8389-5d0a272bd10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iv360-nav-button/button/span[4]</value>
      <webElementGuid>3cae70ca-c901-406c-9b28-d87d2618b4fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
