<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AGENT CODE_userloginid</name>
   <tag></tag>
   <elementGuidId>71ccfdee-c585-4750-b249-161e08557c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userloginid&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userloginid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bcac163-ef9f-4186-a549-040f7e6377a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ISiTextBox ISiWideInput</value>
      <webElementGuid>46cdf4cc-84ae-4c1c-9f92-da603feead84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b170bee7-df0a-433a-827c-ba1d27fa09cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userloginid</value>
      <webElementGuid>cc785773-cce9-460b-8c97-afda86a11390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LogonForm&quot;)/table[1]/tbody[1]/tr[2]/td[@class=&quot;DarkBackground&quot;]/table[1]/tbody[1]/tr[2]/td[1]/input[@class=&quot;ISiTextBox ISiWideInput&quot;]</value>
      <webElementGuid>f54a74cf-cc89-4f10-afe7-28bc8b996f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userloginid']</value>
      <webElementGuid>0db804c7-e140-44d5-83d6-965b6d7c2a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LogonForm']/table/tbody/tr[2]/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>f0ef8bda-15d0-4aaf-80e1-a9d54a7f800d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>de574563-4db7-43cf-913c-6a876f2a32e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userloginid']</value>
      <webElementGuid>e4a847fb-d6fa-4083-937b-a0cbf89ea899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
