<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Recalculate</name>
   <tag></tag>
   <elementGuidId>48bbce57-b4d8-4993-b522-6198d1c75590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='NOSAVEButtonISOReplacementCost_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEButtonISOReplacementCost_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45971900-c446-410e-95fb-e5d9eec28fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn buttonWidget ISiA-PrimaryButton</value>
      <webElementGuid>81992880-e45e-49d0-9534-0b710fe18cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e155b268-895f-4bfb-82fa-df91586a286a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if ((typeof this === 'undefined' || typeof this.id === 'undefined' || this.id=='' || DblClkTrap(this.id,'set'))) { LookupButtonClickJS('2201','1','reusableModalBody','https://alchemytest.cogisi.com/is/root/','1','ISO360');  };</value>
      <webElementGuid>212bb8da-8717-48fd-955b-7da7eb9aaef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEButtonISOReplacementCost_1</value>
      <webElementGuid>35ad0d5e-9dcb-4e3f-a59f-bd9e8279fc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEButtonISOReplacementCost_1</value>
      <webElementGuid>3e2b4af4-4a55-4c3f-97a3-fdf5277dc5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recalculate</value>
      <webElementGuid>99c90b71-c076-43cf-a8f7-2fbeb4293da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEButtonISOReplacementCost_1&quot;)</value>
      <webElementGuid>f497c12e-955f-485d-8fe3-5791c9b3cb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Alchemy360/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>d4d85ba2-60a2-4bf2-ae4f-d0d6bedec41e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='NOSAVEButtonISOReplacementCost_1']</value>
      <webElementGuid>a6f244b7-8a54-4815-9d9b-710487e16f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ISOReplacementCost_1']/div/div/button</value>
      <webElementGuid>f9f93cfb-aabb-4f32-adcb-8c0c5e27fcd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO 360Value Replacement Cost Calculation'])[1]/following::button[1]</value>
      <webElementGuid>6bf15385-2fac-4f10-8df7-ef9f502db5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replacement Cost'])[1]/following::button[1]</value>
      <webElementGuid>432c64ba-97ce-418e-b12a-bbb502438ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional Property Coverages'])[1]/preceding::button[1]</value>
      <webElementGuid>be8e643b-ea84-4ea0-909e-2087d780ed6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional Coverage List (Select All that apply)'])[1]/preceding::button[1]</value>
      <webElementGuid>fbbc01f8-4014-426a-a201-50f48136c74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recalculate']/parent::*</value>
      <webElementGuid>d7214467-200f-4271-8df3-cdfcfde86a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[3]/div/div/button</value>
      <webElementGuid>2d04332c-2aa5-481c-8c5f-507f82261b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'NOSAVEButtonISOReplacementCost_1' and @id = 'NOSAVEButtonISOReplacementCost_1' and (text() = 'Recalculate' or . = 'Recalculate')]</value>
      <webElementGuid>356147f2-e252-4aaa-9de9-aab85c4cab4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
