<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Calculate</name>
   <tag></tag>
   <elementGuidId>efc4bb6f-5fe7-4bfc-87e6-3f7108c7eacc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space()='Calculate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex > div > button.btn.ISiA-PrimaryButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1f7afb4-dece-40b3-b530-1b27bff0f2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ISiA-PrimaryButton</value>
      <webElementGuid>fa7c7640-4839-4b4f-9fb7-0c9652e8a45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>436fe081-eaac-4a86-af57-0b4f67ef56b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ISO360Calculate('https://uat.360-value.com/apps/iv/services/valuation?WSDL', 'https://alchemytest.cogisi.com/is/webservices/', '', 1, 'ISOReplacementCost_1', 'Yes')</value>
      <webElementGuid>49a6567d-eb3e-4895-a292-4f26b40cf286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>6117f664-1284-4574-8cd5-8d3431088e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reusableModalBody&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 py-3 pl-3&quot;]/div[@class=&quot;d-flex&quot;]/div[1]/button[@class=&quot;btn ISiA-PrimaryButton&quot;]</value>
      <webElementGuid>7448f960-b95b-47fd-a2f4-deda8fddd550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Alchemy360/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>a4b5e9c2-c150-46fa-9354-7ddb6a83b114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>bb656b2c-8899-483f-9b12-0bd5dfd640bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reusableModalBody']/div/div/div/div/div[6]/div/div/button</value>
      <webElementGuid>df527914-4107-43e6-a7d2-df88df9a0cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AZ'])[4]/following::button[1]</value>
      <webElementGuid>34ba5076-11fa-4f4e-a353-c892b6043663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YUMA'])[3]/following::button[1]</value>
      <webElementGuid>7a3775d8-ce7c-4a75-9ea6-bf6dee517359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Results'])[1]/preceding::button[1]</value>
      <webElementGuid>20c31ad8-fda2-478e-8708-d4b4fb487cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO 360Value Replacement Cost Calculation'])[2]/preceding::button[2]</value>
      <webElementGuid>5fabdc03-51b6-446d-b125-9035b8301524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calculate']/parent::*</value>
      <webElementGuid>318aa51b-409b-4a60-b807-662ec9c7083d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>0a25ccb0-7446-4af2-93e9-04802160d4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Calculate' or . = 'Calculate')]</value>
      <webElementGuid>cb77485e-03ee-4788-8661-e82d631e1ae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
