<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(including attached)_PRI-XT_COMMERCIA_dd4062</name>
   <tag></tag>
   <elementGuidId>88e6734c-5231-4113-b9fd-865642e37fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PRI-XT_COMMERCIAL_SQUARE_FEET_ALL-VAL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PRI-XT_COMMERCIAL_SQUARE_FEET_ALL-VAL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>917c8c81-8d5f-439c-ba12-788c2d7074f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>28bd8415-d49e-4c37-b7b2-5f7e097a9382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control iv360-integer ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>483c1a3d-7ef3-4699-8776-6d6c87b0aa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PRI-XT_COMMERCIAL_SQUARE_FEET_ALL-VAL</value>
      <webElementGuid>7f1b7ee4-374e-4385-8793-fb14cb5123f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>iv360-questionLabel-XT_COMMERCIAL_SQUARE_FEET_ALL-PRI</value>
      <webElementGuid>edc802e1-eb40-4369-b98e-870cb20e46fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PRI-XT_COMMERCIAL_SQUARE_FEET_ALL-VAL&quot;)</value>
      <webElementGuid>1201857d-8476-4e4a-9855-dd1ed98bfbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PRI-XT_COMMERCIAL_SQUARE_FEET_ALL-VAL']</value>
      <webElementGuid>eaa63a05-11df-425f-b77c-1bdf6ce74c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iv360-cmc-occupancy']/div/iv360-widget-integer/form/input</value>
      <webElementGuid>969fdb85-908e-4b1f-b525-50692563d1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5fbc2016-caf1-4d42-a596-78a02c94a69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PRI-XT_COMMERCIAL_SQUARE_FEET_ALL-VAL']</value>
      <webElementGuid>1366834e-4c4c-4ce9-b7f2-2e7c6204a187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
