<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Store - Drugstore_PRI-XTOL_IWS-SELECT_0</name>
   <tag></tag>
   <elementGuidId>f225c8ff-cf1f-4c91-a03f-7fe4ac0f5ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PRI-XTOL_IWS-SELECT_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PRI-XTOL_IWS-SELECT_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58c89142-3049-4697-a708-f9f6721e42d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-autocomplete-trigger iv360-searchable-select-input iv360-z-auto-blurOnAnswer ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>fd1df47e-67e3-4467-9570-2b01ec719887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PRI-XTOL_IWS-SELECT_0</value>
      <webElementGuid>c0eafbdf-ffab-49d4-8b1a-2e8c269f4740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>iv360-questionLabel-XTOL_IWS-PRI</value>
      <webElementGuid>4c549531-b1cb-4de4-88ff-25a369f6f8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>140aef5a-ee41-4a66-aa22-9e890b98f2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b4e1f1b5-b14e-4c02-9682-9671ded6636b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>4a1c7d86-2867-400d-8e12-5b11a08154d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac5af57a-71ec-47f7-b5f5-622e4df9fa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ebaee0fa-cabe-48d3-86ae-7faad529da9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PRI-XTOL_IWS-SELECT_0&quot;)</value>
      <webElementGuid>3747b2e9-422b-4b45-bdb6-5eb192bab917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PRI-XTOL_IWS-SELECT_0']</value>
      <webElementGuid>58b3f99f-03e7-4602-bd2a-be36dfce46c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PRI-XTOL_IWS']/div/div/div/div[2]/iv360-answer-group/div/form/div/div/div/div[2]/iv360-searchable-select/form/input</value>
      <webElementGuid>e0d7f9ed-a8cd-4f88-9e04-dad3e31eed28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iv360-question-row/div/div/div/div/div[2]/iv360-answer-group/div/form/div/div/div/div[2]/iv360-searchable-select/form/input</value>
      <webElementGuid>9c311640-b3c1-4dc5-8fa0-9db31a03fc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PRI-XTOL_IWS-SELECT_0']</value>
      <webElementGuid>dcc0af2f-06ed-4be2-82a4-51ccf847a0c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
