<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Mansard</name>
   <tag></tag>
   <elementGuidId>84e69245-46b2-4c54-83c3-4410e9b2f2c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-330']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-330</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>9258701c-3a88-49aa-a18c-c7a07e6394c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>273f04d0-23c6-452c-891c-1de609f7415c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-option mdc-list-item iv360-searchable-select-option ng-star-inserted ng-tns-c3964489799-35</value>
      <webElementGuid>ca8e079f-5a31-417a-a82e-dd6135a79024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-330</value>
      <webElementGuid>f6cb492f-8361-4120-b13d-50c238711fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de72b651-f983-4de6-831f-77c3361fbf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43ed0282-0e2f-4f5c-a03c-cffec50d4f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Mansard </value>
      <webElementGuid>3adce1b9-2a8f-473d-a2ef-84644471e7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-330&quot;)</value>
      <webElementGuid>789b98d7-4ee3-49af-89c1-dbe57c65df7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-330']</value>
      <webElementGuid>653bbb7e-2e02-4e61-8c6b-7dccec8723a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-autocomplete-9']/mat-option[6]</value>
      <webElementGuid>dbb84049-798d-4fc9-a451-81af6bc1f7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambrel'])[1]/following::mat-option[1]</value>
      <webElementGuid>bf0b4593-1949-4e8a-9dfb-ee5dea9dabd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hip'])[1]/following::mat-option[2]</value>
      <webElementGuid>d89de525-1706-4cac-8924-8f5c241822bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arched/Barrel'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>d62e9990-ce93-429e-8f79-cfc29dc4d19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[6]</value>
      <webElementGuid>ef718b12-be1e-4126-b2d4-8c7c01f119f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-330' and (text() = ' Mansard ' or . = ' Mansard ')]</value>
      <webElementGuid>60e32154-a630-4a67-b2a9-05b691ef6541</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
