<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Square feet_SquareFootage_1</name>
   <tag></tag>
   <elementGuidId>dfd4b56d-e9d9-4db6-b860-b9ef5869258c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SquareFootage_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SquareFootage_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8adee4ce-aa1c-407d-8a9e-44475359469f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac75dc97-0cb7-4e13-a0c8-6164829861f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>d1a954f4-7aa8-4318-a644-96abb1d90858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SquareFootage_1</value>
      <webElementGuid>642aa424-735b-4e17-b084-b0ec3d2590dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0650c36c-85ea-4a1e-ac86-9b0f58e2ddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SquareFootage_1</value>
      <webElementGuid>d279a1b7-8214-473b-b195-f719b4010bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);ConditionalOnChangeAlert(this,'ISOReplacementCost_1,&lt;>,0;ISOReplacementCost_1,&lt;>,BLANK;AND','_1','Required data has been changed since valuation. Select Get Replacement Cost button to recalculate and provide updated amount. Endorsement will be referred to UW.','false','false');  GlobalOnBlur();   CheckRequired(false);</value>
      <webElementGuid>925b5ca4-c919-4956-8681-9d06a5611ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>  GlobalOnChange(); </value>
      <webElementGuid>a33b8f10-2089-4ac5-a36a-6f2bccc5158b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>ea72bedc-fb5b-45a2-86df-56970ef5a75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>99999</value>
      <webElementGuid>bb7eb980-d4a2-40f9-88d1-b76147558fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>91ff15c7-87e6-48c1-ab9e-b1b685c19a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12d89f6e-fdba-4e71-8cbb-4a80ff8bed78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SquareFootage_1&quot;)</value>
      <webElementGuid>f6d5e836-cff3-4c83-b3a2-d16e5e7db50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO6-NOTUSED/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>0bcb7b05-573c-4d9d-bc85-ccf9af096f23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SquareFootage_1']</value>
      <webElementGuid>7a85ad9b-ebb4-490b-8207-15653b31a7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-SquareFootage_1']/input</value>
      <webElementGuid>12b9e82c-87d5-43fa-9344-e7e310e28d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>007dba7b-8dd0-4f18-8e25-35e635c579c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SquareFootage_1' and @id = 'SquareFootage_1']</value>
      <webElementGuid>d34b6486-9ccc-464c-b622-89877dffa90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
