<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Expiration Date_NOSAVEEXPDATE</name>
   <tag></tag>
   <elementGuidId>8ced80f7-7681-4e13-9719-c53db352009f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEEXPDATE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEEXPDATE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b6fd733-2044-4613-996c-0c06aa993d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76752365-4ffd-4cd3-9b0f-ac996aa280f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateWidget form-control CreditCardDate</value>
      <webElementGuid>1ad633f8-5756-4d12-b0fe-def9a146a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEEXPDATE</value>
      <webElementGuid>f4b4cf78-ddd9-4485-a2de-4b6a83aa3b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEEXPDATE</value>
      <webElementGuid>c52e90f1-ab66-4e36-bcc4-5c4c3a675da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/yyyy</value>
      <webElementGuid>15fd0bc5-63d4-4fbb-bccb-22e8b09b32dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>f38d9760-a98f-4467-99cb-e814e71dc502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isDateJS(this);  GlobalOnBlur(); </value>
      <webElementGuid>2566fe3e-e4c7-42a9-bd55-e00d466221dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskDate(this,event);</value>
      <webElementGuid>ba9a5cc0-a270-4a28-9010-dc400a23e338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEEXPDATE&quot;)</value>
      <webElementGuid>c73c6ba6-ac36-4d62-939b-5fb313e6bfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO6-NOTUSED/Page_/iframe_Enter Credit Card Information_reusab</value>
      <webElementGuid>c37feee5-c629-4a31-9d1d-9a9238a93316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEEXPDATE']</value>
      <webElementGuid>0313c874-4fad-45a0-a3ab-5914f490f75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-EXPDATE']/div[2]/input[2]</value>
      <webElementGuid>892c880e-d9cf-4d78-aff8-33a8e7cb485f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>9f51f04e-bb6a-480a-a287-2423931f8e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NOSAVEEXPDATE' and @name = 'NOSAVEEXPDATE' and @placeholder = 'mm/yyyy']</value>
      <webElementGuid>919242a5-aa78-4010-b556-078ac8d33cc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
