<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_NOTE The address above has beensuccess</name>
   <tag></tag>
   <elementGuidId>e38c5425-724a-4b5a-a1ce-ae0ae6b9c6ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='GMDisplayGeocodeSuccess']/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GMDisplayGeocodeSuccess > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8c0e03f0-6bac-4e6d-8314-b25e64f74fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0f9eb8b2-ba20-413f-b9b7-326b101822b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOTE: The address above has beensuccessfully geocoded.</value>
      <webElementGuid>aeb41a36-bcdd-4de7-8a8d-cc19e7d9c929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GMDisplayGeocodeSuccess&quot;)/td[1]</value>
      <webElementGuid>98eb8019-6e1b-423b-be00-1f5027589698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO6-NOTUSED/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>d78bef16-d323-43af-a9e5-4a9add24a18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='GMDisplayGeocodeSuccess']/td</value>
      <webElementGuid>64bbda7c-58db-4d78-ab05-cd999420ff8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Zip Code:'])[1]/following::td[3]</value>
      <webElementGuid>09e49f8d-16f3-4210-ba0c-0e76a12007ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/preceding::td[1]</value>
      <webElementGuid>2ea7a6d1-9638-4a4d-9cea-ce0f951c2460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::td[1]</value>
      <webElementGuid>6bfd0b89-167b-47bd-adb7-67f4a54b0593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NOTE: The address above has been']/parent::*</value>
      <webElementGuid>af95364a-7af0-4dc5-b136-f9661f941b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td</value>
      <webElementGuid>0c3c552d-5fe1-47dc-912f-b89cf0b29160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'NOTE: The address above has beensuccessfully geocoded.' or . = 'NOTE: The address above has beensuccessfully geocoded.')]</value>
      <webElementGuid>ca9d2e82-78b4-4896-a777-9a234beff853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
