<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AGENT CODE_userloginid</name>
   <tag></tag>
   <elementGuidId>4e0d1cae-8510-4791-8bfc-2ef5e104d86f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userloginid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userloginid&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bc5b0e7-0611-41f6-9e78-bb2176806bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ISiTextBox ISiWideInput</value>
      <webElementGuid>f9fddbb6-fec4-483a-beec-642b1a43f0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8f58b7d-2289-42f2-a692-b2f8b8c36c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userloginid</value>
      <webElementGuid>c018cd50-435a-483e-94c1-e2083d571558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LogonForm&quot;)/table[1]/tbody[1]/tr[2]/td[@class=&quot;DarkBackground&quot;]/table[1]/tbody[1]/tr[2]/td[1]/input[@class=&quot;ISiTextBox ISiWideInput&quot;]</value>
      <webElementGuid>33109756-d2f9-410d-8ee8-e7718953a5c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userloginid']</value>
      <webElementGuid>22c1a361-5693-4007-951b-12dc61354e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LogonForm']/table/tbody/tr[2]/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>899d068f-2d92-465d-aef7-977a7657d5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>f2fc7f8f-f5d0-401e-96f8-cc217b3cbee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userloginid']</value>
      <webElementGuid>282060d4-6f2a-4d4b-8b86-e0aa3bc68836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
