<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_InterestAddress1xxxx3_1</name>
   <tag></tag>
   <elementGuidId>35d26a59-48a2-4076-a485-b3c4c7d2ba44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InterestAddress1xxxx1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InterestAddress1xxxx3_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc089805-f85a-4be5-97cd-998442248b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3995335-2154-4fef-b985-7b1eb173b07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8193fc69-6e7e-4d29-95cb-68672c80e98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address1*</value>
      <webElementGuid>8dfdcca3-a7e6-4413-a712-939c3b67ab7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e7b6dc17-99dd-4d10-b22e-7d46179ad9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InterestAddress1xxxx1_1</value>
      <webElementGuid>a1903192-96e6-41f2-91e9-6c9e84c7240d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InterestAddress1xxxx1_1</value>
      <webElementGuid>70ca0b8c-1bee-4883-ad92-16b61bce762b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);USPSRealtimeAddressValidation('a82741540573558027i15151613s3902970422694160i54330','https://cypresstest.cogisi.com/is/','1701030','Interest','xxxx1_1','Address1',0,0);</value>
      <webElementGuid>ee9bafc8-3176-4f87-a55e-72186523341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Interestxxxx1_1').value='0';</value>
      <webElementGuid>3148c4ed-a596-4242-a844-8a521a8a9f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>f9d5dde1-3be8-4d1a-9a37-32e97bc5c4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InterestAddress1xxxx1_1&quot;)</value>
      <webElementGuid>972d33bf-2833-46f8-801c-999d2a19a1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>a36ef9ec-0a23-4ca0-b702-726c35f20c81</webElementGuid>
   </webElementProperties>
</WebElementEntity>
