<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Extension Flag YES_Content</name>
   <tag></tag>
   <elementGuidId>a90b9209-5ccb-4815-9f67-d00d4e6ca63f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>864ce3ac-c56d-414b-b9d0-3c31347cc6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Content</value>
      <webElementGuid>2cd6a47f-d8f5-4a8a-bc3d-049d7f09cbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>504px</value>
      <webElementGuid>3b5cad25-dc4a-4a57-9cd1-78c0bc847e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>8a7f522b-e1b2-480e-9e0e-a5dad63af049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Content</value>
      <webElementGuid>a27fb756-4721-4cd8-9685-52b4925aeba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Content</value>
      <webElementGuid>d6e595be-b82e-43e9-91e2-1bd528801a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>main.cfm?view=acct&amp;Pages=PostBind&amp;PolicyID=3787&amp;DisplayAcctFrame=false&amp;ViewPrefix=acct_&amp;ClaimID=&amp;QuoteNumber=7890</value>
      <webElementGuid>feb25514-c7e9-4459-82a1-c1a7873610c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>37579188-cc8b-4131-b183-7961ce6e7e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af93daea-e80d-4ad3-8238-8ded08fbbcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f073c18-d969-4b7d-bfdd-b93f1ceb5c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>2f6da348-b23d-4b73-8738-a891ae9c0b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>97143a54-5f20-47ef-8949-d4c5783394e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>dede5a69-cdee-428e-b3ba-ad94c061b26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FrameClass ISiFrameClass</value>
      <webElementGuid>882a8efd-cd55-4a48-b240-134e611457be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)</value>
      <webElementGuid>c947f366-fc4c-418e-a06a-1651781465f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>bcb3da11-4afb-4dd1-9c89-baac2e6acd42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Content']</value>
      <webElementGuid>08c2fbb8-8f11-42c0-99da-d7d475a5a267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PolicyDetailsMainDiv']/iframe</value>
      <webElementGuid>7c744cbe-eeda-4790-8b82-e0a32870edee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7f77a5e3-032e-4387-a9fb-69a04dffa835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'Content' and @title = 'Content' and @name = 'Content' and @src = 'main.cfm?view=acct&amp;Pages=PostBind&amp;PolicyID=3787&amp;DisplayAcctFrame=false&amp;ViewPrefix=acct_&amp;ClaimID=&amp;QuoteNumber=7890']</value>
      <webElementGuid>6f7cb29d-fd64-4f91-b66a-f82a2336e4ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
