<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applicant Middle Name_NOSAVE-INDAppli_24c841</name>
   <tag></tag>
   <elementGuidId>9a27187a-f0a1-4902-a71c-e9e2c3a3a15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantMiddlezzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantMiddlezzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb5435dd-7fee-41bf-b157-d650847d5b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b2e31e3-69d2-4a81-8de4-f5a5eb4a4689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkForUpperCase(this);processAskLastName(this,'ApplicantMiddlezzzz1');</value>
      <webElementGuid>ac0695d7-9fa0-459e-b8de-b6cbf31bfd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ISiA-Force-Uppercase</value>
      <webElementGuid>73af4156-02ce-4a03-b8ff-2a7f773b3763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Middle Name</value>
      <webElementGuid>d42cdfd5-7319-4171-b62b-d03e902e560b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVE-INDApplicantMiddlezzzz1</value>
      <webElementGuid>e2832a2c-8d31-4d52-ae3f-d8b56375c40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantMiddlezzzz1</value>
      <webElementGuid>391e701b-44c4-4c28-938d-2bcc20500668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>b27ba3d5-b514-4c7f-97ca-c1f1df9a2eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantMiddlezzzz1&quot;)</value>
      <webElementGuid>d9cb1463-8e3e-4787-9a6d-214baaeea437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>6a050cfe-e9a6-4974-87b3-82e99be1725c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantMiddlezzzz1']</value>
      <webElementGuid>1d67abae-c852-4a26-9278-0bc5888bf8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantMiddlezzzz1']/input</value>
      <webElementGuid>4d05469e-eff7-4185-8fff-6f6790ca2a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div[2]/input</value>
      <webElementGuid>81b89813-9e36-4817-9b06-4c4a6a3510d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Middle Name' and @name = 'NOSAVE-INDApplicantMiddlezzzz1' and @id = 'ApplicantMiddlezzzz1']</value>
      <webElementGuid>1eac1a31-221b-48f2-a40c-32a120a5c96e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
