<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please choose a name type_NOSAVEAppli_f4d688</name>
   <tag></tag>
   <elementGuidId>375a4f78-5773-4efd-ba0b-469962911819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEApplicantAskzzzz1I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEApplicantAskzzzz1I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20c8ee8d-2a33-4673-82aa-17470546cf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>591f8a21-4526-4e86-a5e3-918835885b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2addae3a-fc81-4bef-ac35-b9816ace8947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEApplicantAskzzzz1</value>
      <webElementGuid>159c9b6e-3e2a-408d-ae00-ed2277c5dfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEApplicantAskzzzz1I</value>
      <webElementGuid>4a19bc56-1057-4f79-ab2a-5d97a968e9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I</value>
      <webElementGuid>0b23d58f-32d6-46e6-82d7-2611b00eb86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);handleNameAsk(this); GlobalCheckDisable(this);</value>
      <webElementGuid>102abf30-c240-4f3d-a779-f987c161f6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);</value>
      <webElementGuid>c7db04eb-19df-47d6-93f9-b0cd68a947ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEApplicantAskzzzz1I&quot;)</value>
      <webElementGuid>893d6ee9-4c82-4ab9-9eea-700a018b4853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>c4f33a32-920a-4a47-ba7e-f861608a9020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEApplicantAskzzzz1I']</value>
      <webElementGuid>184342df-7016-4d2d-a5c1-e1989ff53861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-Applicantzzzz1']/div[3]/input</value>
      <webElementGuid>25d3ec5c-572d-4032-90bb-90d4f8f0d4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input</value>
      <webElementGuid>567c6485-cdd4-48b8-a992-4916451196f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEApplicantAskzzzz1' and @id = 'NOSAVEApplicantAskzzzz1I']</value>
      <webElementGuid>473a1b07-2492-4f3e-aa68-8b8651ffa120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
