<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Square Footage_SquareFootage_1</name>
   <tag></tag>
   <elementGuidId>38481841-f93d-4876-9dc9-43700d91e65f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SquareFootage_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SquareFootage_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ba5bab3-c38e-4ada-857f-c35b7f0d646d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33734756-787c-40e2-91da-549dd2cf051e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>676e355a-46de-4aa8-b48c-81de17fbdf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SquareFootage_1</value>
      <webElementGuid>ac083985-4cb4-425b-9912-10fb730a0cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>beb9ddfc-58dd-416b-9f1a-8b97d4d23164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SquareFootage_1</value>
      <webElementGuid>7cdfb84e-2cfc-4ed0-8c62-e592bd44e446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);   CheckRequired(false);</value>
      <webElementGuid>c949d8d2-e254-4311-bbfb-8c41b7db6365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>328a0e72-1328-4dd6-b048-c7461e261869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>99999</value>
      <webElementGuid>ed0eb6d4-2d53-4730-941d-8483d4acb797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>01fac119-155d-49a9-9428-3eba6139f60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49f0633e-da81-457c-9c79-1cde5b59a236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SquareFootage_1&quot;)</value>
      <webElementGuid>2335249c-52ba-4df7-8683-1ccefe7ce2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>06086655-d980-41a2-904c-efd23e3a0b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SquareFootage_1']</value>
      <webElementGuid>99887fcd-e2aa-461c-b63e-f0d701f55fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-SquareFootage_1']/div[2]/input</value>
      <webElementGuid>e7313386-2b2f-4f7c-b409-92fd786ea399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/input</value>
      <webElementGuid>96450db6-b518-4aab-af04-93325f8ef867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SquareFootage_1' and @id = 'SquareFootage_1']</value>
      <webElementGuid>b88fdf7e-0ea6-425e-a0f1-7df5bacff9cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
