<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applicant First Name_NOSAVE-INDApplic_2cbe29</name>
   <tag></tag>
   <elementGuidId>7ea8bb1d-ab60-4293-8f9e-9430e1307817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantFirstzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantFirstzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d0c1ca4-3a8d-4e86-a296-a7420308514e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f059e66d-7ef0-4c63-aa90-b19207aac812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkForUpperCase(this);CheckRequired(false);processAskLastName(this,'ApplicantFirstzzzz1');</value>
      <webElementGuid>d82194fe-044b-4d6a-adbe-bb43b233cc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ISiA-RequiredInput ISiA-Force-Uppercase</value>
      <webElementGuid>7a320e73-a6d3-4a03-9893-689e52e2267a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>a0fb26e5-7a83-45b6-bd7d-0b24ae5dee81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVE-INDApplicantFirstzzzz1</value>
      <webElementGuid>ff5920ae-80c1-4389-bfac-8e9c42cacaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantFirstzzzz1</value>
      <webElementGuid>a26b430d-187a-475a-ac14-f653e538e57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>ec6975c8-6db8-4ee3-acba-22d606841ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantFirstzzzz1&quot;)</value>
      <webElementGuid>5c1eb621-bb1d-4eea-82c6-8ff5f0bb1073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>3ee10a33-baff-4505-a288-4b60df83f26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantFirstzzzz1']</value>
      <webElementGuid>2af84f56-7ae7-40e8-a68d-d6c3589bf71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantFirstzzzz1']/input</value>
      <webElementGuid>bb4d3988-8083-49b6-896d-b030ec3a0c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div/input</value>
      <webElementGuid>97c6d18e-23ea-46e5-9e73-556075624db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'First Name' and @name = 'NOSAVE-INDApplicantFirstzzzz1' and @id = 'ApplicantFirstzzzz1']</value>
      <webElementGuid>87a3c907-85b9-4dc8-87b2-d59b52c40c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
