<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Term_NOSAVEagentSearchAgentCode</name>
   <tag></tag>
   <elementGuidId>4bac2360-187b-4bc5-b7cb-85a7e44f955a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEagentSearchAgentCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEagentSearchAgentCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be6d3ed8-d6b0-46b6-b0dd-48c596f33538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54782e42-9bc3-4141-93f8-1d7f1222d1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a87439f-6886-4238-a402-f84e776c018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEagentSearchAgentCode</value>
      <webElementGuid>4180cba8-7481-4862-a3b3-6c117761fd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEagentSearchAgentCode</value>
      <webElementGuid>e86a38e0-4c04-4f2d-bae5-8ccc60fb78ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>CheckEntertedInputValue(this,'https://buildersrisktest.cogisi.com/is/', 'AgentCode', 'SubAgentCode');</value>
      <webElementGuid>b385da37-b5a3-40a7-8075-ab16a799e813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEagentSearchAgentCode&quot;)</value>
      <webElementGuid>0b66324c-8cfe-4b17-abfe-2463780633c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>b512e7e6-440a-45c0-b0c5-416f145fe3cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEagentSearchAgentCode']</value>
      <webElementGuid>7cf2016c-aca0-4881-bf69-1d2aeb358618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AgentLookUpModal']/div/div/div[2]/div/div/input</value>
      <webElementGuid>cba6752e-387c-47c1-aa87-b1297cd7d47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>38f3bb55-8ddd-4c00-94ef-4a761d68ba19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NOSAVEagentSearchAgentCode' and @id = 'NOSAVEagentSearchAgentCode']</value>
      <webElementGuid>eea84444-3e2a-4398-b4cc-ae5f170bf0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
