<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Legal name of the builder performing _28237f</name>
   <tag></tag>
   <elementGuidId>cc7cfac1-2252-4835-8a72-4f8f73558cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BuilderName_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BuilderName_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d93fc4c8-7676-4404-974a-f20053acc854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc07dac2-6c44-44d3-8ad9-43553163fd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textWidget ISiA-Force-Uppercase</value>
      <webElementGuid>8bbd014a-7498-48fb-90f0-af376f1b2448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BuilderName_1</value>
      <webElementGuid>8ce9f316-f41e-442c-8bfc-c0dc5d6e2c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17f4a091-9efd-4596-a954-8002f23ff564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BuilderName_1</value>
      <webElementGuid>0a53df4b-6c86-4a12-9669-ab5ec42f75db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validateTextInput(this);   CheckRequired(false);</value>
      <webElementGuid>b9ee8d8e-0581-4ea6-b48c-33e29dd535fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>f3dac8d6-a713-4dd4-a744-5e020d522eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputtype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>d251d0f8-de10-4f83-82c8-5e41ac6c95ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uppercase</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>cd29db01-16f1-4823-8c8c-a492c3a50c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>issensitive</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83244269-500b-407c-a99d-26562a0ea63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchclass</name>
      <type>Main</type>
      <value>Any</value>
      <webElementGuid>57041fa5-6c36-44ff-b052-f48d4c952b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskText(this, event)</value>
      <webElementGuid>4cc004f2-aa02-4718-aa1c-3b9e1fb564a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>91a56a2d-35d8-432d-82ba-a50c05f415eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BuilderName_1&quot;)</value>
      <webElementGuid>c8135e70-4a41-4a17-bfcd-30aa784901ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>c780842b-4fcf-419a-8c37-a5d6c38beb43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BuilderName_1']</value>
      <webElementGuid>e2441d03-498d-4e02-8d10-c1d1b6d3e797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-BuilderName_1']/div/input</value>
      <webElementGuid>59e7be75-e160-425b-93fe-9861c6421cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3acda954-3b8f-4716-99dd-3af7afa361fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'BuilderName_1' and @name = 'BuilderName_1']</value>
      <webElementGuid>aea79318-c621-4dc1-b03e-f28907028154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
