<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_ApplicantEmailzzzz1</name>
   <tag></tag>
   <elementGuidId>39e8b2b0-9b63-42dc-bfd9-6f2a99493576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantEmailzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantEmailzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fcf40f8-3729-49b9-bf4d-af47fb822990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb8b5090-624a-4d19-be67-628fb32ddf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d9b40359-522a-4f05-a1ce-56da1bb2cc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>c0d2b81a-e4a4-4ade-9205-09f2ad9538e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>52be09f6-8389-47fe-bfc7-58ea8fe7eca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckEmail(this);   CheckRequired(false);</value>
      <webElementGuid>81eb125d-f94e-48b8-8482-65ec3af25cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantEmailzzzz1&quot;)</value>
      <webElementGuid>805b3643-fbbc-4cb0-b36c-5951f3f24f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR TX/Page_/iframe_RTR Quotes_MainIS38test</value>
      <webElementGuid>707468fc-4105-4fda-8ab4-818265ac2ebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantEmailzzzz1']</value>
      <webElementGuid>ddaee5b1-b2d0-4383-b5d2-2bc6bfc65313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantEmailzzzz1']/div[2]/input</value>
      <webElementGuid>020f1fee-411e-4a1c-820a-20044f0952a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>c26f1037-d893-4735-b53e-cf989c1b2b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantEmailzzzz1' and @id = 'ApplicantEmailzzzz1']</value>
      <webElementGuid>aac4a5e7-8add-451f-919a-1bcb35ba8613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
