<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WaterHeaterYear</name>
   <tag></tag>
   <elementGuidId>0337e3ea-c4c1-4087-811e-073fba116e18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='YearWaterHeater_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b947c66b-ed5a-402f-a958-78a1fc59f919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84c90624-faae-48cc-83a6-83dcd9ef3719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget fromPageValidated</value>
      <webElementGuid>c9cb2f55-f258-434a-b2a8-f432055e0ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SquareFootage_1</value>
      <webElementGuid>0a32f91f-5733-4bfa-94bf-da59f4f1c321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5a22068-9db8-448c-bc92-3faefe669b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SquareFootage_1</value>
      <webElementGuid>9e0c92f1-680d-4f0c-a8c1-ca283c402602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);; GlobalOnBlur();   CheckRequired(false);</value>
      <webElementGuid>9bf0007f-c635-409b-b0a1-e7dabcc8db3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>; GlobalOnChange(); </value>
      <webElementGuid>4913b90c-5c93-48d3-a00a-8a16908f7cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>268b961f-710c-4e7d-81bf-79ee193bcc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>popover464756</value>
      <webElementGuid>6686ea96-377a-4cbc-b185-91835b4e0f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SquareFootage_1&quot;)</value>
      <webElementGuid>243a0270-b818-4c79-8f95-198ffcd369b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cypress 4/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>7d466e48-26e8-46ce-82ba-3f597025b8ab</webElementGuid>
   </webElementProperties>
</WebElementEntity>
