<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEGQForSale_1</name>
   <tag></tag>
   <elementGuidId>9f5da056-b5d5-46fd-b883-558e5da52d1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEGQForSale_1No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEGQForSale_1No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a88d927-33d3-4881-b835-72143db0df66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e12d9d90-2a15-4480-88b6-2a13354c8f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4f024fde-8379-43ee-9f66-4959270bff38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>236f5ed1-1618-415a-b9bf-7a4bcb5581d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEGQForSale_1</value>
      <webElementGuid>c76c3a3e-2d42-4487-94ce-3f710124a458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEGQForSale_1No</value>
      <webElementGuid>c0a3b25f-643c-48aa-a2aa-41169e03e7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>61eda685-cf57-496a-8447-f4c536e3f797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);  GlobalOnChange(); </value>
      <webElementGuid>d0777bbc-383d-42bb-a731-7807b69c563c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>b6f94390-ce3f-44f4-984b-84559723a3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalOnBlur();   CheckRequired(false);</value>
      <webElementGuid>8cd20057-547c-4bd3-94d9-453a23031f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEGQForSale_1No&quot;)</value>
      <webElementGuid>2ba03689-43b2-4307-ab46-9212fd68bd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO3/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>95f26f18-4ef9-4b87-93bf-37b57709ee75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEGQForSale_1No']</value>
      <webElementGuid>dc7cc6cc-5251-47c3-a69c-1081336fe6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-GQForSale_1']/div[2]/input</value>
      <webElementGuid>c3f3875d-a7e2-432d-afc8-b8d09a9858b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div[2]/div[2]/input</value>
      <webElementGuid>245db886-d1af-43f0-b360-ff8c09a46ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEGQForSale_1' and @id = 'NOSAVEGQForSale_1No']</value>
      <webElementGuid>35b77c8e-dc21-4639-9dd3-8d86bd117366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
