<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEGQRenovation_1</name>
   <tag></tag>
   <elementGuidId>da18a592-da2c-4a34-9d5d-3dc04f6cd515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEGQRenovation_1No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEGQRenovation_1No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caf8942c-9f79-4f0b-9813-07f1698df8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>0701ed83-e50a-4765-b83a-10c815f34ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1f280451-6d69-4f50-bbcf-4e8321d44a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc75a9a3-7654-41bb-ae16-320f27cbd9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEGQRenovation_1</value>
      <webElementGuid>727fa00d-7a08-4b18-b823-f1741684c724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEGQRenovation_1No</value>
      <webElementGuid>cc28963e-6b85-481b-9af8-2ef1179b83f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>12a80336-b696-4273-b1ab-8d442c98d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);  GlobalOnChange();  GlobalCheckDisable(this);</value>
      <webElementGuid>14a42d9c-5f36-4e4f-aa6f-a315df3daa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>76f84cac-27c6-4893-a7e9-4735ed838986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalOnBlur();  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>41c2c0bd-62f5-4add-bb98-d35f4957cdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEGQRenovation_1No&quot;)</value>
      <webElementGuid>78554a72-7ebd-4416-97ff-d77a9bc76143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO3/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>a0ed3324-4ffb-4477-a660-d36190fc0c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEGQRenovation_1No']</value>
      <webElementGuid>e02265e9-6d87-4fba-b8c2-7c172c7181be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-GQRenovation_1']/div[2]/input</value>
      <webElementGuid>1a3dedac-5512-4688-8992-075053efb0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/div[2]/input</value>
      <webElementGuid>071feb18-3e3c-4dd9-8cf4-3350aca66b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEGQRenovation_1' and @id = 'NOSAVEGQRenovation_1No']</value>
      <webElementGuid>82a78a38-e081-4462-bebe-be40045a34a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
