<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVESwimmingPool_1</name>
   <tag></tag>
   <elementGuidId>cbc587b6-d1dc-4454-b9c2-8af97150e321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVESwimmingPool_1No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVESwimmingPool_1No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5886c3b6-5d02-4a0d-af56-d67c4debfbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>0c8847bc-9c93-4b84-a8fd-0dd323b0684a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>75dcb058-042e-4feb-a704-d23fabfa8c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eec26c0d-a1a6-4b69-9377-1d8ee1363e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVESwimmingPool_1</value>
      <webElementGuid>4e610cb5-be51-4784-9397-adf56468c535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVESwimmingPool_1No</value>
      <webElementGuid>fb7137b8-f27e-44d0-b24f-d2201f9c318d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>8e460c9e-6b2a-4ea6-901d-ee83545d23ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);  GlobalOnChange();  GlobalCheckDisable(this);</value>
      <webElementGuid>9c1296e9-007b-4386-b585-03d47e4a8057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>e6176236-f576-4b5b-8cfc-9ad9da4e546e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalOnBlur();  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>08c982c2-4bbb-4799-9463-c9641f8d6cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVESwimmingPool_1No&quot;)</value>
      <webElementGuid>c78206c8-a829-4eb3-8d7b-be233f297f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO3/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>658fe4e9-5774-4d41-abf6-ff0dfa4eb8b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVESwimmingPool_1No']</value>
      <webElementGuid>b26a35e1-151d-4892-af8b-29c2f28182d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-SwimmingPool_1']/div[2]/input</value>
      <webElementGuid>9c9a8bce-94c5-46e9-b38f-ab1797285fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div[2]/div[2]/input</value>
      <webElementGuid>b55db5c4-ed44-4234-8d57-9e7a4d42a331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVESwimmingPool_1' and @id = 'NOSAVESwimmingPool_1No']</value>
      <webElementGuid>6a9ed6ac-a301-4c22-a513-8fadfb1a35f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
