<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_ApplicantHomePhonezzzz1</name>
   <tag></tag>
   <elementGuidId>12164d83-e0c1-4ab4-af6d-1d5aa7605412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantHomePhonezzzz1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ApplicantHomePhonezzzz1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b3404dc-b29b-43ed-a695-79581137d7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7b41461-e76b-4e08-8ef7-3be980fc0cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>ddd-ddd-dddd</value>
      <webElementGuid>1551511e-6681-4477-ab9a-354ddc285672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control phoneWidget</value>
      <webElementGuid>82d3f5d2-5d48-49a8-b6b8-e98503f2be93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantHomePhonezzzz1</value>
      <webElementGuid>df13e9d0-2b64-41c6-9d01-baf002c1df55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>d024bc8a-c600-4d70-8ecd-14a5ac936201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantHomePhonezzzz1</value>
      <webElementGuid>823027e3-7026-47dc-9c01-77a8661e5ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validatePhoneNumber(this);</value>
      <webElementGuid>bb6f381e-cdb1-4574-8a7c-f5ebf37805a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskPhoneNumber(this, event);</value>
      <webElementGuid>95d3a975-14a7-48b0-a6bb-87a2f7e80821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantHomePhonezzzz1&quot;)</value>
      <webElementGuid>e2007b7e-506d-4aca-9341-30cfb314baa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO3/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>abe7fa3b-f016-4ce1-8f85-4716423ad5d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantHomePhonezzzz1']</value>
      <webElementGuid>e2c96d72-100e-42a3-bdf7-ea12cf716a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ApplicantHomePhonezzzz1']/input</value>
      <webElementGuid>2801d4d5-b3c2-4478-9cdb-43dd7c884588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>5f801b59-c1e1-44eb-a01a-db4c94e0dbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantHomePhonezzzz1' and @id = 'ApplicantHomePhonezzzz1']</value>
      <webElementGuid>ce8ad3c0-dee4-4458-8ce9-f6568bbb943f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
