<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Roofing Updates_LastRoofUpdate_1</name>
   <tag></tag>
   <elementGuidId>b646a794-9cd3-4499-8871-971c855a3571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LastRoofUpdate_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LastRoofUpdate_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da2f728a-103f-47eb-841f-cc6621f5bc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdba2f9b-f18b-4fee-8b14-d62a14e52d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>6ea5aa36-e9b9-427f-911b-286bc60e7515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LastRoofUpdate_1</value>
      <webElementGuid>5298cd86-9d5f-422d-917a-695984671a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed1501a5-013c-47d3-b7b3-1f65f0370b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LastRoofUpdate_1</value>
      <webElementGuid>f72d25be-431e-447c-90ef-6eea00fb822c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this); </value>
      <webElementGuid>a815d4ce-824e-4baa-80f1-14e8853da2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>b139e4dc-582d-4dba-b781-39e39928c6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>1800</value>
      <webElementGuid>6dcdf386-db18-4816-9d1b-20b294992ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b9be5142-d6d5-4dbe-92ba-2af7dfb391eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f7566e7-ca39-449c-b59f-af29a9ca5ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LastRoofUpdate_1&quot;)</value>
      <webElementGuid>79ed0bc7-2f94-4fec-b0e0-9644f5ea9ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>5fc8d129-a1fd-47a0-969f-7c11084b67a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LastRoofUpdate_1']</value>
      <webElementGuid>756cc728-d2c3-4349-8aa1-285fb621bc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-LastRoofUpdate_1']/div[2]/input</value>
      <webElementGuid>22d95382-d332-4c36-be6f-cbdc9a37a939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div[2]/input</value>
      <webElementGuid>a98a461d-5faf-4746-8258-e1beac8fd940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'LastRoofUpdate_1' and @id = 'LastRoofUpdate_1']</value>
      <webElementGuid>d36d9421-f384-4138-a392-194239b3b252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
