<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_ApplicantEmailzzzz1</name>
   <tag></tag>
   <elementGuidId>220e66b8-1258-4836-85b0-6947658d63fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantEmailzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantEmailzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95569800-8a96-4c2b-87cb-cb02e100107b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>acc0e120-e7f4-4dfb-a2e6-4f54e9ae33f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a54305e8-f989-4cb8-bb6b-7c156fa4345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>b28f01bf-3b6a-44df-8ee2-e85733ee3096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>137d5171-278f-4f22-a755-79729cb5b489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckEmail(this);   CheckRequired(false);</value>
      <webElementGuid>dab8264e-719f-4943-a3c4-19de00fab532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantEmailzzzz1&quot;)</value>
      <webElementGuid>8596fe09-44ed-4dbc-a5c7-a9daf9c64d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>7b7ce57d-2bf6-4378-a502-27f1ece94426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantEmailzzzz1']</value>
      <webElementGuid>4d53587f-b08e-42db-a742-e2ef00bfcbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantEmailzzzz1']/div[2]/input</value>
      <webElementGuid>59f00d98-7797-4ae0-b10a-feea59105e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>aaad4049-366d-411f-aa89-88fe35022b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantEmailzzzz1' and @id = 'ApplicantEmailzzzz1']</value>
      <webElementGuid>b68501ee-75ca-4b9a-92bf-ff655f222115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
