<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employees_Employees</name>
   <tag></tag>
   <elementGuidId>a342cb9b-9c4d-40e2-ba0c-0fb4589a6790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Employees</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Employees']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20c7713e-3be0-4bd4-bdb6-655ab75e6c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0137446e-6a04-4842-a4cc-b04f1ed06db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>5375f223-5f32-42be-8ca4-bad3e0b67687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>15e1ac4d-c831-4f08-a162-54fff217ba2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>386031f9-14db-4512-85bc-7f9cbc9cc8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0ff45e4f-6651-4f81-a952-b107a3c7939b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>4b9802e0-29d9-4165-b87a-ee396a5b3abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>e588b268-a924-4071-a269-0117c89f18c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this); </value>
      <webElementGuid>cfad0231-06fe-4ea5-b94f-10eb424113ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GlobalCalculated(this); </value>
      <webElementGuid>e04f57ef-70ff-4f07-a207-09f61b5faf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>5ccef5ca-7eed-48b9-bd7d-60e68fecaa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87016909-f669-4208-b7db-5e4b6ad6cdf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Employees&quot;)</value>
      <webElementGuid>9a1ea6c5-7371-4e1e-a70e-22f698eb8c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>29b946da-1c33-473f-886f-6e1c40053e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Employees']</value>
      <webElementGuid>0e922549-3203-4def-9da7-e5eb3ba2d81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-Employees']/input</value>
      <webElementGuid>d8ad2b1c-6024-4862-856b-12ef1dc00f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/input</value>
      <webElementGuid>8a0d64a1-ed8a-4632-a477-62ecc9cf9ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Employees' and @id = 'Employees']</value>
      <webElementGuid>cc1c9995-feed-463c-b6a8-ae78a9602ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
