<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_InterestNamexxxx1</name>
   <tag></tag>
   <elementGuidId>b7225dee-731b-4a13-9049-112a77cabf46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InterestNamexxxx1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InterestNamexxxx1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3bb3ebc-1f0e-4fa6-8e51-853b2a551a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9cd20e6-9985-489a-8739-e47627b02a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textWidget ISiA-Force-Uppercase</value>
      <webElementGuid>65c3a036-6e18-4268-b611-caf57253ea1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InterestNamexxxx1</value>
      <webElementGuid>0f5fc336-82ca-4f40-bea0-5d739b1afdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>20a5be8b-80a8-486d-8c0e-ce567f17e09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InterestNamexxxx1</value>
      <webElementGuid>a0a84621-1d78-4bee-9fae-13ee4f608e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validateTextInput(this);   CheckRequired(false);</value>
      <webElementGuid>1bbd2c4c-923b-4854-80d8-c2afb60e854c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>188a93f1-78b9-4ad5-ab60-f27764e9f8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputtype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>456de046-90f8-4503-8acf-e99c8a85fb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uppercase</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>f3d3b4ea-5052-43fb-ab9e-17139642e2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>issensitive</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1cdf8d6a-01a2-4a17-81c3-18d374361bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchclass</name>
      <type>Main</type>
      <value>Any</value>
      <webElementGuid>82349d57-6985-439b-b7bc-d7ce302708a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskText(this, event)</value>
      <webElementGuid>a541be1f-eb0e-4642-a44e-9df5dde3bb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InterestNamexxxx1&quot;)</value>
      <webElementGuid>91a8b67a-f1c7-4637-963a-d60ff3b483dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>b877e89f-d15d-41d1-9816-8be7bac1ea13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InterestNamexxxx1']</value>
      <webElementGuid>d61c6f5f-c174-4eab-9bd3-8072f6f4f908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-InterestNamexxxx1']/div/input</value>
      <webElementGuid>01e7278c-1a06-4ec8-9547-7e344ff49ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>21b98eed-9b1e-4bb5-b57c-653439872050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InterestNamexxxx1' and @name = 'InterestNamexxxx1']</value>
      <webElementGuid>63800b9e-9911-4d5c-b624-af332ef0a287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
