<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inspection Contact Phone Number_TEXT10</name>
   <tag></tag>
   <elementGuidId>9baf8339-fdfb-4175-8ea5-74fc8a02ed58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TEXT10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TEXT10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18b2f9de-df5d-486d-8906-6bf5fff8a25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4d450a1-f63a-4d39-90a7-5a991c1682d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>ddd-ddd-dddd</value>
      <webElementGuid>29a83e8b-aacf-465e-8e3b-51282eea5bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control phoneWidget</value>
      <webElementGuid>e75c9363-07a0-462f-b8e8-4fcf50c4faf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TEXT10</value>
      <webElementGuid>de373474-b184-4c96-b912-895a7584cd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>fc658f8b-498f-4d92-b57c-e4b68ccc4ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TEXT10</value>
      <webElementGuid>654986af-6468-494c-87d0-216236e0b766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validatePhoneNumber(this);</value>
      <webElementGuid>cf0f821f-649c-4660-bf2e-a4edc7e8d60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskPhoneNumber(this, event);</value>
      <webElementGuid>fb947fe0-3f4d-4888-981c-5dfa27cd335e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TEXT10&quot;)</value>
      <webElementGuid>4be3365d-85bd-4ab6-8e00-613ad3f738f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>d9f0a9dc-4b59-490e-b970-d52e085b50c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TEXT10']</value>
      <webElementGuid>15f2d5bb-4d04-4f9a-b77d-d3fb49a077cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-TEXT10']/input</value>
      <webElementGuid>f514987b-1043-493a-9468-99cf76977fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/input</value>
      <webElementGuid>07c7d24e-2635-42b2-b7ee-58cf04bac276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TEXT10' and @id = 'TEXT10']</value>
      <webElementGuid>22e3a1e5-5245-4dca-8403-1216fa637063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
