<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CBP 40 01_ProductLimit_1</name>
   <tag></tag>
   <elementGuidId>eb4d93a5-82f6-4f26-853f-7e1f07f81be6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductLimit_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductLimit_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02ea2a0a-bba2-45be-bcad-c4f67d4ccd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7b10c4c-f8c3-4639-9ec7-ec00df29afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>1de41610-6dbc-4897-b384-0f344de7abe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductLimit_1</value>
      <webElementGuid>a3e05ff5-589b-4911-987e-f482543863cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1fce675-be7a-4f07-9efc-d4cf2cdc443b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductLimit_1</value>
      <webElementGuid>8e87058e-c55f-446e-accb-e498d6a8ab41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>7bf0f0ff-f2e7-49a1-8f2d-891de9d1c5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>  GlobalCheckDisable(this);</value>
      <webElementGuid>1832736a-7be2-44f7-a856-bb67806156fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>6efd155e-9f42-4a34-96ee-97eec2da57a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>53af4e5b-35aa-4b6e-b3e4-248054c9ccd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dc23ad2d-4c1f-4cd7-bd40-58325e701ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductLimit_1&quot;)</value>
      <webElementGuid>780e0003-c884-4c61-8fe2-0df25e56e9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>2bcd658c-3d5d-468b-99c2-57374734f9a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductLimit_1']</value>
      <webElementGuid>59598cde-99a5-49ec-b2b0-657ed0579033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ProductLimit_1']/input</value>
      <webElementGuid>7ec61f62-c4c1-4dcf-b567-e70ef358fe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/input</value>
      <webElementGuid>363bd68a-d6e3-4dbc-a271-ffd8050b73fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ProductLimit_1' and @id = 'ProductLimit_1']</value>
      <webElementGuid>9d7c5899-c816-4ca0-baaf-bfd7aa11bb9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
