<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Partner Last Name_CoApplicantLastzzzz1</name>
   <tag></tag>
   <elementGuidId>f5dd57ea-3a5e-4704-8cb2-4833b72b86de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CoApplicantLastzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CoApplicantLastzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f640278-0105-4335-8392-7bd9e998c6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff5592f6-234c-4f13-bfa7-a0dbc0b82f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckRequired(false);</value>
      <webElementGuid>4638e787-b061-49b3-b15b-9a681969a221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ISiA-RequiredInput ISiA-Force-Uppercase</value>
      <webElementGuid>8cb9c067-778b-4f75-ac8b-d9baebd01000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>af25e1fa-4d10-46ca-999a-6f63ec3c14aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoApplicantLastzzzz1</value>
      <webElementGuid>92b62706-479a-4b2e-baf7-22d260b0d208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoApplicantLastzzzz1</value>
      <webElementGuid>5ed77fa7-1297-4022-8a63-95cf9879e503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4f1c45b2-d08c-4da2-9b00-a6c38d0ee5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoApplicantLastzzzz1&quot;)</value>
      <webElementGuid>e7db14cc-b8b4-4f85-bc7d-4e474bb8238d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>1128b51a-6de6-4001-84b9-0bae1ae4e717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CoApplicantLastzzzz1']</value>
      <webElementGuid>7f0b7d89-5d44-494f-876e-7e27177ba21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-CoApplicantLastzzzz1']/input</value>
      <webElementGuid>c6380165-406d-4250-b303-750551bb74b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/input</value>
      <webElementGuid>ff0d5057-8eb1-4c41-9128-f0febca8c185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Last Name' and @name = 'CoApplicantLastzzzz1' and @id = 'CoApplicantLastzzzz1']</value>
      <webElementGuid>aa9b910d-d336-46dc-80de-ca958083a36a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
