<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applicant First Name_ApplicantFirstzzzz1</name>
   <tag></tag>
   <elementGuidId>0c4382db-7a9e-4870-92d8-6c43f23fae1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantFirstzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantFirstzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69529522-afac-4671-8c23-9f04135c4ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32dd30b2-d1ba-4f28-81d4-fbeaade7c588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckRequired(false);</value>
      <webElementGuid>8c49963f-ea7a-4a4e-af39-6bf2fd189578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ISiA-RequiredInput ISiA-Force-Uppercase</value>
      <webElementGuid>9b99565c-b838-46e0-9bb0-3d903c0e9a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>99fdc921-9784-4a69-8b1b-a8f278911cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantFirstzzzz1</value>
      <webElementGuid>e3268e70-fd49-49af-aadf-1b8fe944c524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantFirstzzzz1</value>
      <webElementGuid>cbd83702-bf42-4bf6-8221-ee35ddca51a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>debeb99b-71a5-482b-9adb-46c6f27c72d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantFirstzzzz1&quot;)</value>
      <webElementGuid>f2fbda17-d9ad-4b7d-8c49-772ac8473984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>7888e368-138c-462a-9c78-0c00300f45d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantFirstzzzz1']</value>
      <webElementGuid>e30e26ca-85f3-4723-a2b5-26d36e58d17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantFirstzzzz1']/input</value>
      <webElementGuid>092c30f5-3482-4d4c-a9ee-65bcd65ffe2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>9b8687de-59f4-4edb-8cef-067f05ddf50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'First Name' and @name = 'ApplicantFirstzzzz1' and @id = 'ApplicantFirstzzzz1']</value>
      <webElementGuid>cf478c15-9e9c-48b2-9a84-a4cdb4e9938f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
