<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Dishonesty_NOSAVEDishonestyLmt</name>
   <tag></tag>
   <elementGuidId>96f1a82a-92c0-49d4-9de0-0a92401ddfe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEDishonestyLmt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEDishonestyLmt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6a6b5ef-0ee2-4706-91a2-3ce95b53661e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>24a6224c-515e-4e08-a9c2-f906f04e620a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>25000</value>
      <webElementGuid>695d2d7a-8c90-431a-a042-244c5a7ca710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEDishonestyLmt</value>
      <webElementGuid>ae83035c-6fb9-4859-87f1-fd95bb1c34af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEDishonestyLmt</value>
      <webElementGuid>1a0e7750-e9d1-4837-b518-3dc93ae15d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>UpdateCheckbox('DishonestyLmt','25000','10000');  GlobalCheckDisable(this);</value>
      <webElementGuid>7f0b116c-655d-4542-a137-4d3f5287a88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);</value>
      <webElementGuid>10352330-d18a-4628-a33a-1bddeb64f6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEDishonestyLmt&quot;)</value>
      <webElementGuid>36d9a1c5-5c0d-4a90-9cc5-3295fe63ae53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>d24b2575-bedf-406c-997d-15d963888aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEDishonestyLmt']</value>
      <webElementGuid>49606081-75a4-42f5-891d-89975bfb5615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-DishonestyLmt']/input[2]</value>
      <webElementGuid>58bd9ccd-15dc-4a17-ac9c-16a6cc8af1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div[2]/input[2]</value>
      <webElementGuid>3425bd7d-e23e-4743-8eb3-da09758d5ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'NOSAVEDishonestyLmt' and @id = 'NOSAVEDishonestyLmt']</value>
      <webElementGuid>b1986960-9aaa-43c7-9f23-ae558b054b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
