<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City, State, Zip, Zip4_LocationZip_1</name>
   <tag></tag>
   <elementGuidId>7bc622f7-0d85-49d0-ba48-cf807010c3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LocationZip_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LocationZip_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>156d78bb-165a-4b58-9fc7-5e183a1bccb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b72c377b-973a-4690-ac9c-604d1da626f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberAddressWidget</value>
      <webElementGuid>e8418cd6-fce0-457b-bddd-b052c175b4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip Code*</value>
      <webElementGuid>b6c2418b-45e9-4d64-8dba-edab58fbcb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1ad6eef4-bb14-437e-8304-77ca2379e6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocationZip_1</value>
      <webElementGuid>fd5a7f08-c1a9-436c-bf78-2418866ec4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LocationZip_1</value>
      <webElementGuid>4ed78e4f-8ed9-433f-b2d3-26ac87194b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);ISiA_QuickZipCheck(this);USPSRealtimeAddressValidation('a68768558542518765i49962214s2932970492472841i29721','https://alchemytest.cogisi.com/is/','100115','Location','_1','Zip',0,0);CheckRequired(false);</value>
      <webElementGuid>2eb2deff-e1a2-4687-976b-2b2eb2c72d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Location_1').value='0';</value>
      <webElementGuid>a25ed0a9-1ce1-482e-9a39-afa191880956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>PositiveInteger</value>
      <webElementGuid>dab56ce5-19fd-4ea5-94f8-bfb85f862454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LocationZip_1&quot;)</value>
      <webElementGuid>117251f0-df68-46ea-b8b1-0668fdded5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>5b089370-4a13-47c3-a212-ebf40bf9bab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LocationZip_1']</value>
      <webElementGuid>b9c2b59b-b898-4cda-a731-0e77c058661f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-LocationZip_1']/div/input</value>
      <webElementGuid>4c456b4d-cfb3-4c7d-b2c2-880b12a59de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div[5]/div[4]/div/input</value>
      <webElementGuid>4bcb6b85-65e4-47dd-a02c-a94a1caa8b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Zip Code*' and @name = 'LocationZip_1' and @id = 'LocationZip_1']</value>
      <webElementGuid>18953279-dbfe-4ed7-80a6-2093fcc657f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
