<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AddInterestZip</name>
   <tag></tag>
   <elementGuidId>ec43219f-fcd3-4f92-bbea-f1227d44a289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InterestZipxxxx1_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InterestZipxxxx1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65a49dd6-4997-4bcc-a178-7a9743a97085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df28df5b-786e-407f-80b9-9dfeef62a0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberAddressWidget</value>
      <webElementGuid>b5c7a18f-ad57-43c6-a3f7-66573d67bd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip Code*</value>
      <webElementGuid>67f8f282-80e8-41e0-bf0b-e4cd12dbf0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>319888e6-3c94-4ae3-a856-6a97b12f3601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InterestZipxxxx1</value>
      <webElementGuid>6d6bd3d7-bb55-4f8a-a943-177362171843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InterestZipxxxx1</value>
      <webElementGuid>04edb28a-13fe-4eef-9c55-bcccf36cc995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);ISiA_QuickZipCheck(this);USPSRealtimeAddressValidation('a68768558542518765i49962214s2932970492472841i29721','https://alchemytest.cogisi.com/is/','8001030','Interest','xxxx1','Zip',0,0);</value>
      <webElementGuid>645520e3-da83-4d26-a289-fcfd48988c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Interestxxxx1').value='0';</value>
      <webElementGuid>dabb9645-5178-4d73-8e6a-375ce551898f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>PositiveInteger</value>
      <webElementGuid>398a2630-3819-4dd7-b7ba-c147d72221d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InterestZipxxxx1&quot;)</value>
      <webElementGuid>8e66f701-46f4-4d17-abc3-b386b3501ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>38875bfc-788d-43b2-88a0-f46294382339</webElementGuid>
   </webElementProperties>
</WebElementEntity>
