<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__SurplusTax</name>
   <tag></tag>
   <elementGuidId>4334eee3-a7c1-4050-a9a5-29ecdd1c1064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SurplusTax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SurplusTax']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83859184-fd00-442e-a47a-2545ad5cf08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e52bdb3-2670-44aa-a2a8-f4344f7cc73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget </value>
      <webElementGuid>2858f531-a749-4d9f-b8f9-65a40113fd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SurplusTax</value>
      <webElementGuid>11c9041f-701f-4bab-a0b0-7935205bb329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46f1ea77-53ad-4d45-a374-1d35bd489b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabletohide</name>
      <type>Main</type>
      <value>DisableElement_SurplusTax</value>
      <webElementGuid>78393723-3d81-4408-b541-e4c2cddef4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SurplusTax</value>
      <webElementGuid>3dbabba1-a8be-41e6-84e0-90e6c10bbe6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this); </value>
      <webElementGuid>160bc277-fb0a-446a-852d-53b318d9b0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>isNumberJS(this); </value>
      <webElementGuid>a27cefde-670f-4794-b27f-93f936c4b637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>42c3c293-aca7-47c7-8de8-6345f82ff1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a905b1da-75fb-48ad-a11a-f9349f587902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SurplusTax&quot;)</value>
      <webElementGuid>97a2f069-3963-4c53-af54-e887197c5591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>32d11bd7-3636-4ae8-9e02-a03cbe7943e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SurplusTax']</value>
      <webElementGuid>9bd1ba17-a3ca-4345-98e6-3488026886d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-SurplusTax']/div/input</value>
      <webElementGuid>e2f55290-f63c-4acc-b4bc-e6a17a9650ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/input</value>
      <webElementGuid>389f498f-5335-4be0-8cba-75508b12ebc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SurplusTax' and @id = 'SurplusTax']</value>
      <webElementGuid>1b6f0f1c-a7b2-4d9b-a452-e79d0cacc634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
