<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_EffectiveDate</name>
   <tag></tag>
   <elementGuidId>faa960e4-95e5-43f9-be4e-bab6002e08ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EffectiveDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EffectiveDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4978f2d-2380-4c20-a1c3-48f64eae84db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe0e6fe6-12cc-4f56-933f-1b2dd86a3be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EffectiveDate</value>
      <webElementGuid>1674a1c6-d742-4d32-b7cf-85a3c44c5aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EffectiveDate</value>
      <webElementGuid>fb4edccf-8a6a-4110-b2a6-a50a3588d685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12/19/2022</value>
      <webElementGuid>5f154582-320b-43b8-a66f-fa60c4e953e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>; chkDate(this) </value>
      <webElementGuid>79efe7f2-256a-46f6-bdc4-c1ad728a1ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskDate(this)</value>
      <webElementGuid>525c398d-028c-407d-aeea-dec92c6d39e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>838f94d4-89ff-4584-95c1-cd32169706fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hasDatepicker</value>
      <webElementGuid>144e9093-b61c-4ee0-9a69-7997f1cd3cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EffectiveDate&quot;)</value>
      <webElementGuid>a892fb66-2365-4ab2-857f-0ad3290a73dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>e5645ce4-0b16-4a56-a48e-b10ce5be1477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EffectiveDate']</value>
      <webElementGuid>8fcf6ba9-60f2-4668-9502-b27e4120defe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='StartANewQuoteFormTable']/tbody/tr/td[2]/input</value>
      <webElementGuid>d4a6729f-4bee-4a44-9a71-01b8715eda67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>130722b5-954e-4d9c-a019-d21dc4ff5804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'EffectiveDate' and @name = 'EffectiveDate' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>eeef861d-1c64-4edb-860d-a781ed9797ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
