<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are all exterior doors to the buildin_cf60fc</name>
   <tag></tag>
   <elementGuidId>232e03d8-a75d-4d68-b8a9-97b2cc1aba48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEHasReinforcedSteelYes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEHasReinforcedSteelYes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ad1a54c-c378-4141-ab26-ef2abf9a869e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e75ec755-42a8-45ef-b94d-2aa2fdcdcdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dfeb72c3-6e06-4a7d-a318-ae73d294b31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c151685-e12f-44a6-8e8a-18400b3cfee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEHasReinforcedSteel</value>
      <webElementGuid>35f84ccc-698b-4a6d-926a-2701b7f1e8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEHasReinforcedSteelYes</value>
      <webElementGuid>b0b61792-2a7f-40e5-9a30-3fd7b89db5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>d00da43c-461d-4ca7-a606-6c959c5fb3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this); </value>
      <webElementGuid>e28ac4d0-4920-410b-aec5-563c32c8195e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>58d5f14f-62b0-4113-92f0-133df572ea38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>  CheckRequired(false);</value>
      <webElementGuid>cc4fef4c-353c-4ae4-9469-ee76ad2630fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEHasReinforcedSteelYes&quot;)</value>
      <webElementGuid>3ffaf3e8-d57b-4ebd-a5de-eeb4b65ce3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>ead62f23-bd31-4e67-b362-860def10a744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEHasReinforcedSteelYes']</value>
      <webElementGuid>d6ca2541-4ea7-4fe5-99b7-5b2d6e81100c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-HasReinforcedSteel']/div/input</value>
      <webElementGuid>8e722e23-0674-43d1-b3ec-7f69c0889651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div[2]/div/input</value>
      <webElementGuid>c37821bc-472f-4a0f-9ceb-e9d7e68290b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEHasReinforcedSteel' and @id = 'NOSAVEHasReinforcedSteelYes']</value>
      <webElementGuid>57b5ce23-384d-4837-a1bd-04104c5f4a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
