<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location Address_LocationAddress1_1</name>
   <tag></tag>
   <elementGuidId>32e712e1-6fe3-490f-9d61-45d4813f7580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LocationAddress1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LocationAddress1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86b60382-7287-43a0-bb34-39f1b0d1130d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bfdfc41-8ce4-44b6-9c97-14adf44f180c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>90804708-f662-40e3-8289-213b4d0b1343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address1*</value>
      <webElementGuid>0f7b081c-18d1-4100-8af6-5ad7831ef957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>38f44302-5c37-4e71-85c4-e34c1552b4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocationAddress1_1</value>
      <webElementGuid>9aa5d57c-f860-4ce2-a650-e265fbd7125f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LocationAddress1_1</value>
      <webElementGuid>79ad54ee-e434-4870-8906-2a98e8d119cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);USPSRealtimeAddressValidation('a68768558542518765i49962214s2932970492472841i29721','https://alchemytest.cogisi.com/is/','100115','Location','_1','Address1',0,0);CheckRequired(false);</value>
      <webElementGuid>1e8a1077-26fb-434c-82a1-264af2bc8c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Location_1').value='0';</value>
      <webElementGuid>f3b23c1e-0b8e-4977-b8ff-75a69b105511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>7a767b24-f85e-4918-890a-091c8ba68154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LocationAddress1_1&quot;)</value>
      <webElementGuid>5bcc1072-64ff-4862-9055-867e2a509721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>95efa114-466b-4410-902a-f1a53cf1f447</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LocationAddress1_1']</value>
      <webElementGuid>bda1ba5b-32a0-478f-a76b-93a8458495f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-LocationAddress1_1']/div/input</value>
      <webElementGuid>f944cf8c-b396-4123-a767-1976f6862a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>813e2b5d-3fff-4d75-ab58-35b61ee67e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Address1*' and @name = 'LocationAddress1_1' and @id = 'LocationAddress1_1']</value>
      <webElementGuid>da8a29b9-322d-4d87-bdce-a58bf13c9c0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
