<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Does the applicant no existing violations</name>
   <tag></tag>
   <elementGuidId>c168a2e5-899e-4491-9632-f4fe3c48a11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVERunsBGChecksYes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEAdminViolationYes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c36b5551-ef18-4c23-a3c3-3ca0b1d3f715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>380046b6-f983-4b42-aa88-cbfba04065e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>df7055a7-385c-4d18-9af5-ce8855cb5e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47f6c421-9c93-4f6c-a1f0-2090113279eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVERunsBGChecks</value>
      <webElementGuid>c69071c2-5513-45c1-9d5b-9b352c2a7654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVERunsBGChecksYes</value>
      <webElementGuid>b075bc81-b2da-417b-baf1-6558a15c5158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>f2deae07-4062-4949-9941-9fca86c16a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this); </value>
      <webElementGuid>9728fed5-ff97-453f-b956-e1b96efec238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>e3dce9a5-e321-4bc5-812b-36c8512d2c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>  CheckRequired(false);</value>
      <webElementGuid>278f91a9-453b-4496-8bb7-a1d500da2cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVERunsBGChecksYes&quot;)</value>
      <webElementGuid>1384c491-5c9f-4467-bc4d-54dd0647523b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>b62470c7-0dd3-4a7c-95da-056ffce2649c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
