<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Partner First Name_CoApplicantFirstzzzz1</name>
   <tag></tag>
   <elementGuidId>cc719b00-8571-4c5c-b7dd-a959f42c62e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CoApplicantFirstzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CoApplicantFirstzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea811dce-6d13-4342-8093-08d0a761f26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51b0c9a2-a5a1-4f85-83e4-8bd01dd8a303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckRequired(false);</value>
      <webElementGuid>ef9c9003-08a2-4d0c-9848-60b5403cb47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ISiA-RequiredInput ISiA-Force-Uppercase</value>
      <webElementGuid>55b3420b-a89d-440d-b0e8-47a9672c32d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>39af35b5-ee29-420a-8502-6206e6715b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoApplicantFirstzzzz1</value>
      <webElementGuid>b4d8a293-9949-40b9-9161-d15fefc8175d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoApplicantFirstzzzz1</value>
      <webElementGuid>13bca26c-0400-47aa-80e4-e34bae332d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>dccef96b-4167-4f7b-8580-9d462f9ea7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoApplicantFirstzzzz1&quot;)</value>
      <webElementGuid>ad7bc24f-4b6b-46a6-b05d-2bb0a93f9695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>228d478d-d727-47c8-83f4-214c2711dedd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CoApplicantFirstzzzz1']</value>
      <webElementGuid>93d9f117-af59-4573-a3c6-c473b8076bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-CoApplicantFirstzzzz1']/input</value>
      <webElementGuid>453d387d-15a2-4b5d-9747-50b41460b9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a6cdeb39-188c-427e-82de-1fb2ed717cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'First Name' and @name = 'CoApplicantFirstzzzz1' and @id = 'CoApplicantFirstzzzz1']</value>
      <webElementGuid>f7129d6f-c26b-4fae-af63-01605ab691ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
