<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ValuableRecords</name>
   <tag></tag>
   <elementGuidId>9c7a7e19-c791-414e-b396-2a46d7092278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValuableRecords</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValuableRecords']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d458250a-9ffd-4f34-83c3-dfa082927907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67294b2b-8e3e-4d4d-b860-9f04e5657f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget </value>
      <webElementGuid>76c57fde-2ca6-4916-ade7-a2b279264fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValuableRecords</value>
      <webElementGuid>287d05b4-832b-409b-b45b-f7b21a9427e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>10000.00</value>
      <webElementGuid>f1d6b088-4ea9-44c8-881d-62090e4bc163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e46feafa-7990-4b59-ae64-ce2c94bf2678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabletohide</name>
      <type>Main</type>
      <value>DisableElement_ValuableRecords</value>
      <webElementGuid>e8fa6f52-220d-4355-8495-b95caba43725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValuableRecords</value>
      <webElementGuid>27ebfad6-80ee-49c4-b6e3-b6da50a216d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10000.00</value>
      <webElementGuid>6eae3159-209a-41dd-8cdf-e0ab218745bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this); </value>
      <webElementGuid>a1ebdda3-b35d-4b77-8417-bf8ff2e6af22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>Money</value>
      <webElementGuid>f439b0a3-e92d-4a68-bd7c-4fc4c9190883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>50000.00</value>
      <webElementGuid>c7fe1291-0adb-40e3-82d4-863ae5dad275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>10000.00</value>
      <webElementGuid>310df757-28e9-4cce-b720-f02ddbec6c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>50914089-af1e-480d-a1ef-560031631168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValuableRecords&quot;)</value>
      <webElementGuid>66fd8fd3-7593-4a78-a408-2fc4fdc31b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>65500ca3-e82a-4b8e-941a-a0e28c3ff0bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValuableRecords']</value>
      <webElementGuid>c114450e-94bb-4663-a986-6ce694b21370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ValuableRecords']/div/input</value>
      <webElementGuid>5443ac44-0240-4970-9d6a-37316d107821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[6]/div/input</value>
      <webElementGuid>87edc486-7776-443c-b93e-874a170aabd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ValuableRecords' and @id = 'ValuableRecords']</value>
      <webElementGuid>e5f7a595-ab43-4b7c-a531-af0080cbeb3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
