<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FEIN_FEIN</name>
   <tag></tag>
   <elementGuidId>2a35bd71-2b6e-43cc-8587-a47ea7600783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FEINzzzz1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FEIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcca03c7-a4db-40fe-81e3-dd5b07c12288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f3981ad-f6d6-47b8-b563-8c6aeef62dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textWidget ISiA-Force-Uppercase</value>
      <webElementGuid>b31301d1-1712-42a8-99be-a49bef83a4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FEIN</value>
      <webElementGuid>39c0ffa3-e9bf-4141-9588-a8b619d5fb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>20157735-0cfd-4f3b-b886-aba3083cf9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FEIN</value>
      <webElementGuid>a2168a58-d14b-4113-b98b-cd09f7257054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validateTextInput(this); </value>
      <webElementGuid>23eae933-d09b-4bc8-bb01-3fb75580c502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>19c06e40-0d3d-420b-aba6-41677b9a645b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputtype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>6fc92046-bbb1-40df-923d-aa518f860ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uppercase</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>91b098df-b9c4-4c84-a7d4-287939a68acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>issensitive</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>176a1edb-4337-4770-aca7-7407d671aafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchclass</name>
      <type>Main</type>
      <value>Any</value>
      <webElementGuid>154e6b26-54e7-4ac4-92ee-3a5afbc02f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskText(this, event)</value>
      <webElementGuid>c7be50ed-1b7d-4ab2-a0de-42d2b054ec7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>23824745-b825-4512-9f90-c34707cbdf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FEIN&quot;)</value>
      <webElementGuid>7e2ccff0-ccd0-45a1-8024-7b9d95b40c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cannabis/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>b7346790-8dfc-4092-830d-adbf51a237cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FEIN']</value>
      <webElementGuid>0a3ed8df-e324-46ac-b117-0a23af3637a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-FEIN']/div[2]/div/input</value>
      <webElementGuid>fccf2c38-c4b7-48a2-a147-73d7af4f115c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>a7aca081-8ce9-4d3f-873e-fb579000205f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FEIN' and @name = 'FEIN']</value>
      <webElementGuid>9bea3877-fa05-41e9-bd07-7b88cc0bd5e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
