<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_InterestZipxxxx2_1</name>
   <tag></tag>
   <elementGuidId>01bea6a8-4c2d-402b-b474-cd992d21ce55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InterestZipxxxx1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InterestZipxxxx2_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da8cf14a-12a7-4587-8298-8c35bb22220f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9db047bf-3158-46a6-9154-7e8f11beb826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberAddressWidget</value>
      <webElementGuid>a7278d61-5891-4c47-8cde-631be634382b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip Code*</value>
      <webElementGuid>1fae3697-5823-4a99-b99d-77d7d104679b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bfa7b4ef-8ed5-4bec-8e63-635ac6708625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InterestZipxxxx1_1</value>
      <webElementGuid>fa8f8aab-3f41-4e38-9d93-8a119d64dc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InterestZipxxxx1_1</value>
      <webElementGuid>9c592573-98b0-4b88-93c6-c720f826d0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);ISiA_QuickZipCheck(this);USPSRealtimeAddressValidation('a82741540573558027i15151613s3902970422694160i54330','https://cypresstest.cogisi.com/is/','1701030','Interest','xxxx1_1','Zip',0,0);</value>
      <webElementGuid>2098a612-bcfa-417e-befa-99d643234225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Interestxxxx1_1').value='0';</value>
      <webElementGuid>d04833a7-c9ac-4024-8307-73bf36804d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>PositiveInteger</value>
      <webElementGuid>a124d001-d383-47ce-94c6-607ffba6752f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InterestZipxxxx1_1&quot;)</value>
      <webElementGuid>f8389e86-7e48-45ea-b661-49041944acf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>9d43b16d-fb3d-4376-81a8-c353e1bfff5d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
