<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No_NOSAVESuspiciousActivity_1</name>
   <tag></tag>
   <elementGuidId>a446e0f7-e1e1-4181-aec1-17b525fc25b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVESuspiciousActivity_1Yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVESuspiciousActivity_1Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5301ccbc-dfe6-483c-8f7d-a9f73766e430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>5b9fd392-04db-4ceb-ac41-af66bf96e5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>43e40955-6d5a-4937-b23d-9f4ea1e39960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>942e39f5-7814-4698-b35e-f70711cd5153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVESuspiciousActivity_1</value>
      <webElementGuid>2eb16052-a840-45d0-9080-4c8bb2a85950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVESuspiciousActivity_1Yes</value>
      <webElementGuid>5004a554-c8a7-4844-bf62-ad83886d3306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>3ac654ee-9425-464e-aeb0-62df38ca6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);  GlobalCheckDisable(this);</value>
      <webElementGuid>fb2f9a3a-f414-4308-afe7-6b8b7031cc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>1c68b528-f754-46d6-a598-024d9b50cdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>8f1fab8f-1817-4085-9b43-edd35a77c717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVESuspiciousActivity_1Yes&quot;)</value>
      <webElementGuid>5ebe22f5-9b42-43d1-9cf2-028c38742e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BR FL/Page_/securityQuestions/iframe_System FAQ_MainIS38test</value>
      <webElementGuid>6818ca4f-c055-4266-b114-0b133311e6f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVESuspiciousActivity_1Yes']</value>
      <webElementGuid>8dfc8cc7-3029-4824-a965-d76e20133b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-SuspiciousActivity_1']/div/input</value>
      <webElementGuid>0c552a39-e57a-4800-a1c5-f3b61634e0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/div/input</value>
      <webElementGuid>d438c617-9b6e-4f17-a16a-f775ace9c8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVESuspiciousActivity_1' and @id = 'NOSAVESuspiciousActivity_1Yes']</value>
      <webElementGuid>40e49e3f-ae14-4b66-83fe-75a0ccbe502d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
