<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_USERNAME_userloginname</name>
   <tag></tag>
   <elementGuidId>f827e1d0-3eea-4057-b9da-fda7f43f96d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userloginname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userloginname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dd8d232-9e93-4adc-b293-7449ff8de766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ISiTextBox ISiWideInput</value>
      <webElementGuid>271250d7-ceed-4c6c-b8e2-8a12e1c9be86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>522ddeef-6101-4c66-9750-5448f7818531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userloginname</value>
      <webElementGuid>1807603c-db80-43f0-95c9-d2fa288f2cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LogonForm&quot;)/table[1]/tbody[1]/tr[2]/td[@class=&quot;DarkBackground&quot;]/table[1]/tbody[1]/tr[4]/td[1]/input[@class=&quot;ISiTextBox ISiWideInput&quot;]</value>
      <webElementGuid>e182dd49-c8b5-441b-bf53-93b958c5a974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userloginname']</value>
      <webElementGuid>1464dfad-78b1-4af5-9321-90b718f1e6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LogonForm']/table/tbody/tr[2]/td/table/tbody/tr[4]/td/input</value>
      <webElementGuid>9def3a46-2754-4074-81af-fe068779e283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>be0cf7e4-a5de-4250-b04a-222ec854cff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userloginname']</value>
      <webElementGuid>f042e354-65fa-494c-b20a-14d468d3d12f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
