<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DwellingLimit_1</name>
   <tag></tag>
   <elementGuidId>ad99274d-0799-4324-9954-77b24c52fd74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DwellingLimit_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DwellingLimit_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ad0c83f-77c2-4b19-82c5-15b645643239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a417f00-4ba5-4fae-8665-a41d37fca811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget </value>
      <webElementGuid>e39e3355-af34-4c9a-a11c-ef0e7beb9508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DwellingLimit_1</value>
      <webElementGuid>738f82bb-c577-4198-9e69-7537e94cab8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>40000.00</value>
      <webElementGuid>18df815a-6e18-4960-bc5f-c3f0459ad7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d788a01-318f-4f41-b392-012944447581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabletohide</name>
      <type>Main</type>
      <value>DisableElement_DwellingLimit_1</value>
      <webElementGuid>d170b9eb-7bbf-4edf-a610-6fec3af2f149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DwellingLimit_1</value>
      <webElementGuid>9a00b637-e4aa-43f1-90cf-61785bc56942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>40000.00</value>
      <webElementGuid>24045861-a6d8-485d-b204-26f12dd059b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);  GlobalOnBlur();   CheckRequired(false);</value>
      <webElementGuid>d88fa1d0-8df6-445e-9408-da3e0cc3934d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>  GlobalOnChange(); </value>
      <webElementGuid>353a04d2-9d05-48aa-9390-0dbaad3a155b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>1edb298e-c33d-4a2f-ac8a-0953bd3da9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>35000.00</value>
      <webElementGuid>93399a8c-e0f2-4397-9414-882d1a1219b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>459b497a-d079-4f01-94e3-fd89465c691c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DwellingLimit_1&quot;)</value>
      <webElementGuid>769f34f9-237c-439e-b58f-e4465e61b85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>a8605c02-b432-4c0f-b51b-eb01cbacb4e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DwellingLimit_1']</value>
      <webElementGuid>f59be7eb-1e0b-498c-89eb-f0bc7195deaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-DwellingLimit_1']/div[2]/div/input</value>
      <webElementGuid>896dde48-08a4-49f1-b00a-e745e13e70a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>8b88a847-014d-4e44-8724-2f986ee76863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DwellingLimit_1' and @id = 'DwellingLimit_1']</value>
      <webElementGuid>fb85161f-8502-40d8-827d-b909347d2b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
