<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEGQDeclineInsurance_1</name>
   <tag></tag>
   <elementGuidId>e884fcca-f437-4aa3-80f7-0522c4f0fc30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEGQDeclineInsurance_1No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEGQDeclineInsurance_1No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>129953d3-18c1-466e-a5c3-be332fbf0b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>9d3e0619-b8f9-478a-af1a-70cd2dda192b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>81f85303-772e-44d2-bfa8-147ce5e48fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b362cbc-ee5e-4b4b-8716-d0c4f636383f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEGQDeclineInsurance_1</value>
      <webElementGuid>97921689-dbfe-4de9-93b9-29659aae689a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEGQDeclineInsurance_1No</value>
      <webElementGuid>296e1f5b-dc6f-43f0-bc56-59f8c05dd797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>5e3f0483-e4f5-43bc-bfaf-e83b6e8f5acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);  GlobalOnChange();  GlobalCheckDisable(this);</value>
      <webElementGuid>e645eb7a-985c-4957-abc7-73c5987bd8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>a2dd0810-44b7-4fd3-8802-c7f9eb9584f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalOnBlur();  GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>ff993421-6512-4a7e-b75a-f8b3e0c3d0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEGQDeclineInsurance_1No&quot;)</value>
      <webElementGuid>6871276f-a66e-4411-90df-d0184388c631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>bf4dff66-1fc5-4060-950f-78cccdb59bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEGQDeclineInsurance_1No']</value>
      <webElementGuid>cd27ffab-f0ea-4d9b-8807-944eea58aa98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-GQDeclineInsurance_1']/div[2]/input</value>
      <webElementGuid>6f4c11e7-33b9-478b-8e98-c77efcae95e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div[2]/div[2]/input</value>
      <webElementGuid>0aa1de13-7f3f-4156-9430-f94f42e22762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEGQDeclineInsurance_1' and @id = 'NOSAVEGQDeclineInsurance_1No']</value>
      <webElementGuid>bcbd4c83-c669-467d-8351-d5440e1bb480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
