<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enter Credit Card Information</name>
   <tag></tag>
   <elementGuidId>3a57b23e-3b5b-4504-8cf5-3c542cc6feb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='NOSAVEButtonnone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEButtonnone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b167d9b-bda7-439a-b100-8e152ff2aae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn buttonWidget ISiA-PrimaryButton</value>
      <webElementGuid>2184af39-f55d-437f-8ff8-8c5490be8172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0011b1cc-1872-49e2-957d-463a51d7019b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enter Credit Card Information</value>
      <webElementGuid>332e60b6-4d51-422f-b022-8344db9ce735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if ((typeof this === 'undefined' || typeof this.id === 'undefined' || this.id=='' || DblClkTrap(this.id,'set'))) { StartCC('90','2','reusableiFrame','https://cypresstest.cogisi.com/is/root/','NOSAVEButtonnone','Update Credit Card Information','1');  };</value>
      <webElementGuid>3b8222d5-e343-4a1c-a5ee-7a3e4856a0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEButtonnone</value>
      <webElementGuid>90edd4cc-be36-4b39-a641-6e64d8989909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEButtonnone</value>
      <webElementGuid>b162191e-59da-4624-9083-65a2bfe76063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter Credit Card Information</value>
      <webElementGuid>1db52551-91db-4a7b-86b0-c91fc21b3e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEButtonnone&quot;)</value>
      <webElementGuid>39ec3548-e46e-4730-9b5c-688d99d203ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO6/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>b3b35516-cf72-4f37-8fe0-41524cd2339d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='NOSAVEButtonnone']</value>
      <webElementGuid>d619dba6-1551-4bf0-b5ca-eecfb99366c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-none80919']/button</value>
      <webElementGuid>9e10d3ce-c437-4a4c-bbe2-55989c5a423b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collect Credit Card Information'])[1]/following::button[1]</value>
      <webElementGuid>db51e916-dc3a-451d-8aff-e49b06b754a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Re-enter Account Number'])[1]/following::button[1]</value>
      <webElementGuid>014285c6-0aa9-4dca-bc4c-bc4980c65a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorized User Agreement'])[1]/preceding::button[1]</value>
      <webElementGuid>42cee585-3f7d-4601-9552-39dedb7cbb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Number'])[1]/preceding::button[1]</value>
      <webElementGuid>091dbf8d-c8f8-4bef-bfdb-7e32097cbe04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Credit Card Information']/parent::*</value>
      <webElementGuid>d34b4431-6d42-46f5-8f29-698254690271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>ee4629f2-1567-4315-8df7-a96c3a4b89bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'NOSAVEButtonnone' and @id = 'NOSAVEButtonnone' and (text() = 'Enter Credit Card Information' or . = 'Enter Credit Card Information')]</value>
      <webElementGuid>ff3a8d75-bcc1-4b59-b1a7-97273e5d0aa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
