<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Quote Number 1049475</name>
   <tag></tag>
   <elementGuidId>eb18e53a-ceca-4e91-80c5-6fbfa911db07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Wrapper-Left-QuoteNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Wrapper-Left-QuoteNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9aca347-3b0a-4d53-9d50-e71c118dabe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Wrapper-Left-QuoteNumber</value>
      <webElementGuid>f4308924-ab2b-415b-828a-1bd9e8c1ea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-3 p-1   </value>
      <webElementGuid>201fe045-f5b3-4e8d-8009-837dedb7fc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quote Number: 1049475  </value>
      <webElementGuid>2e023186-7844-4ed0-b797-03b679c07941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Wrapper-Left-QuoteNumber&quot;)</value>
      <webElementGuid>a1955d4f-b874-4e35-8e24-b3a0763c058d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO6/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>bd19cfd9-d253-4947-b850-d6b82090cf2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-QuoteNumber']</value>
      <webElementGuid>361ce6db-124e-464a-8b85-d3f51558d1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>8ef42dfb-0ea7-4e93-9ab1-859010ce266f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/following::div[7]</value>
      <webElementGuid>87d816ed-9421-4ba1-bba0-d03a8e525dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate and Continue >'])[1]/following::div[8]</value>
      <webElementGuid>d426bc94-a9ed-4676-bca3-0d19b401e750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MCO: 87'])[1]/preceding::div[1]</value>
      <webElementGuid>434cffc8-bf16-48cb-8733-494f32bfa2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HO Form: HO6'])[1]/preceding::div[2]</value>
      <webElementGuid>a10f6606-8d58-4fc5-b6fe-0b6406b13bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quote Number: 1049475']/parent::*</value>
      <webElementGuid>5c83b040-727f-460f-9f48-d94ddcb23a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div</value>
      <webElementGuid>6258c7a3-0b62-4339-b9d4-acb259c1c2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Wrapper-Left-QuoteNumber' and (text() = 'Quote Number: 1049475  ' or . = 'Quote Number: 1049475  ')]</value>
      <webElementGuid>5f7da4b8-0f09-47c7-9935-0b2e67c4456c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
