<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Agent Transaction Report_MainIS21test</name>
   <tag></tag>
   <elementGuidId>11262827-e423-4ff7-8d0d-d5ead4b3119d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainIS21test</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='MainIS21test']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6dc7ddf2-a7d4-4c9e-b9f1-1b058005ddf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainIS21test</value>
      <webElementGuid>ce758bf3-a3ca-4123-99f0-02e2786e8bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main</value>
      <webElementGuid>ad4b8221-dc7c-4809-b387-9a2572d78110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./main.cfm?view=home&amp;TabView=</value>
      <webElementGuid>d883202e-f079-4b87-9ab3-ecd956166876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MainIS21test</value>
      <webElementGuid>4c2976b8-bd02-4381-a896-df48fd75acfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>7b589cb5-a3d1-4e26-b400-31784ac740c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b401b5d0-2327-4dfc-bd6a-db3b55904d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4188acaa-979f-4ba5-a9ef-2747a1b3bcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>1245b7d3-57d1-44e4-8e23-d281c5c9d261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>05445886-b25d-4976-a7d2-555340753ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f17b2cf7-1306-43c3-a28f-7cb1b4ebf01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>711px</value>
      <webElementGuid>951e0f27-6d1e-4411-93b7-bc5ec9ff48f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainIS21test&quot;)</value>
      <webElementGuid>f10f6c5c-f751-4207-b8f5-cb810ceae76f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='MainIS21test']</value>
      <webElementGuid>859ed6ba-6be6-4b9a-93b3-9d7ca78e9db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='MainFrameContainer']/iframe</value>
      <webElementGuid>6b01e8a8-16cc-4d53-8935-ae540633320e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7f237c79-a37f-46df-a6a5-c2c3a727ac1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'MainIS21test' and @title = 'Main' and @src = './main.cfm?view=home&amp;TabView=' and @name = 'MainIS21test']</value>
      <webElementGuid>a0687c0c-22ea-4a81-b080-acf6151926fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
