<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_ApplicantLast</name>
   <tag></tag>
   <elementGuidId>c3f4d01e-5870-4917-a542-60bf7042c5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantLast']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ApplicantLast</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e685da0-6d39-47c7-9fa3-58e0ac7b59b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29a675d2-b1b9-4729-86d2-8163523be8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantLast</value>
      <webElementGuid>67fee211-4f9c-4894-b815-ca8290f33902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantLast</value>
      <webElementGuid>2907169e-37b7-4fb6-b559-cfc552c3f7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c19105fc-d4f4-4d29-b586-5f785d1a175b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ac0883e9-b283-4456-bab2-d3ab55067d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GMJSDataManager('0',document.getElementById('RealtimeGeocodingProviderSelector').value);MakeVerifyStreetAddressCall('https://cypresstest.cogisi.com/is/',this.form,'Applicant','','',getMostRelevantPolicyTypeCodeValue(document.getElementById('PolicyTypeCode'),'',''),'0'); </value>
      <webElementGuid>965041e7-9dc7-4241-91e9-8543f0621ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>; chkQuotes(this); UpperCase(this) </value>
      <webElementGuid>9efad9e0-1ae0-420e-bc6f-a216edd357ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantLast&quot;)</value>
      <webElementGuid>8fe407e6-43bf-4763-bfb0-087b2f9ba822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO6/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>b561a324-5c96-4ec5-b287-f9a5f72d3d4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantLast']</value>
      <webElementGuid>065f8e32-6157-462d-a058-08e4b186b169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='QuoteAddress6']/td[2]/input</value>
      <webElementGuid>b8311481-8300-447f-a928-94501e35e87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>236dbd82-3d75-4aa4-869d-3be39cad67df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantLast' and @id = 'ApplicantLast']</value>
      <webElementGuid>b0a32d2e-ef9a-4eda-bc39-cef24556ff00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
