<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEUnsettledClaim_1</name>
   <tag></tag>
   <elementGuidId>7b84854c-0ec4-440b-9f6c-412a6cb2723b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEUnsettledClaim_1No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEUnsettledClaim_1No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c72abbd6-5616-4f5a-ac91-f8f469692b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d6d778d7-af71-4795-8839-b86fea670e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>781ca491-5d6a-4dd5-8e03-bc03cc1f3999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43223fbc-c0d8-4a77-9574-58eac9aecb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEUnsettledClaim_1</value>
      <webElementGuid>f3dc4589-cb7d-4b2d-801a-0d65610c6dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEUnsettledClaim_1No</value>
      <webElementGuid>3f95e431-f1dd-4031-8141-8f9dfa124048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>3f9a3440-b85d-4417-8e7d-285de46620f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);  GlobalOnChange(); </value>
      <webElementGuid>49f0ab52-ca45-4679-8a0e-b9959ac60c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>e0b34cf4-3f55-42b0-9a89-8b79b0fe3bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalOnBlur();   CheckRequired(false);</value>
      <webElementGuid>67f3af62-89e5-44e6-85ee-76bd4cfb61af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEUnsettledClaim_1No&quot;)</value>
      <webElementGuid>0ee38099-c483-48bb-8f80-5aca45258656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX EG HO6/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>770fd51d-1f3e-4cce-9e42-beeede1bf243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEUnsettledClaim_1No']</value>
      <webElementGuid>1e2779ab-8aea-402c-9f6e-dbafbe6de85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-UnsettledClaim_1']/div[2]/input</value>
      <webElementGuid>0b722acb-9315-4524-ab80-126e63fcad9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/div/div[2]/div[2]/input</value>
      <webElementGuid>662b2a40-cb40-4477-8b4c-d62089d5ee3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEUnsettledClaim_1' and @id = 'NOSAVEUnsettledClaim_1No']</value>
      <webElementGuid>b266014c-1500-4211-9856-77b1572c9f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
