<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Standard_mat-radio-outer-circle_1_2</name>
   <tag></tag>
   <elementGuidId>71514168-381a-48dd-877f-42db40b61452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='XT_INTERIOR_QUALITY-OPTION_2']/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#XT_INTERIOR_QUALITY-OPTION_2 > label.mat-radio-label > span.mat-radio-container > span.mat-radio-outer-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>667a2094-0154-4064-b3b1-5e1a86ec7c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-outer-circle</value>
      <webElementGuid>c59995e8-38ad-4233-8a6b-4042dbdbd04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;XT_INTERIOR_QUALITY-OPTION_2&quot;)/label[@class=&quot;mat-radio-label&quot;]/span[@class=&quot;mat-radio-container&quot;]/span[@class=&quot;mat-radio-outer-circle&quot;]</value>
      <webElementGuid>b9f37a66-2255-40d8-827f-7a2816b7dac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='XT_INTERIOR_QUALITY-OPTION_2']/label/span/span</value>
      <webElementGuid>836e6469-b2eb-4064-84f3-f051cd944755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iv360-quality-section[3]/div/div/div/mat-radio-group/mat-radio-button[3]/label/span/span</value>
      <webElementGuid>d93c6d89-4def-4421-9e18-14ccea550504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
