<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loan Number_LoanNumberxxxx4_1</name>
   <tag></tag>
   <elementGuidId>0fb273e3-352e-4155-8c04-fdb7e43eb35b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoanNumberxxxx1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoanNumberxxxx4_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e33d582-d8cc-4dfd-baa2-f33ea16f32c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27a0a91c-f585-4f18-9350-f41b9ed41de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control textWidget ISiA-Force-Uppercase</value>
      <webElementGuid>3dabc74e-726a-42ea-b471-db03867d3710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoanNumberxxxx1_1</value>
      <webElementGuid>dd976eae-70cf-45c7-8e77-00759e4b7b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>20f59ecd-d777-4458-8c38-d4792d0df510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoanNumberxxxx1_1</value>
      <webElementGuid>219c459c-1bd6-442f-b1f3-a73b3ef8f23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validateTextInput(this);   CheckRequired(false);</value>
      <webElementGuid>bca30f26-cb6a-49b0-ac56-952a8af5ff0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>9dddb9f6-74ea-41c7-b74f-d0b7fb2da94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputtype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>06019455-1c1f-4b6b-8972-a3a7b6cfc52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uppercase</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>432eee6a-82ed-4897-87af-709e92ce6263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>issensitive</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ea51a14-50c9-4285-bda8-b7bab869fd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchclass</name>
      <type>Main</type>
      <value>Any</value>
      <webElementGuid>d65b58fa-d890-42e5-959e-0a919900e390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>maskText(this, event)</value>
      <webElementGuid>bf7fc908-f87e-4e66-9bd1-de0cda1157fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>aba85a79-6eee-4fd6-b359-5f13fd52d8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanNumberxxxx1_1&quot;)</value>
      <webElementGuid>e3e647f7-4a9c-461c-b5d3-438cb3ed29f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>ac60c241-4f2b-46ef-bf4a-4c29c5e07bbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoanNumberxxxx1_1']</value>
      <webElementGuid>bdc437cd-aa20-46a6-b887-d1987c431b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-LoanNumberxxxx1_1']/div/input</value>
      <webElementGuid>05c0502d-cae5-4af2-996f-78e5c5c02fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/input</value>
      <webElementGuid>7bef4443-879d-42ef-863b-826ea8b38296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'LoanNumberxxxx1_1' and @name = 'LoanNumberxxxx1_1']</value>
      <webElementGuid>c037e981-4b33-4a2d-8cad-b6f5690056d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
