<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MORE</name>
   <tag></tag>
   <elementGuidId>5edbfb35-c06b-409e-a0df-1ebb49f765a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c45936b-3db4-4211-91e1-65d2cb661192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navButton</value>
      <webElementGuid>a2e734aa-2c8d-495a-bdc4-3d4cb1a60dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ISiSilverButton</value>
      <webElementGuid>1c15b7cb-2e94-4961-aba4-36f2bef24b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MORE ↓</value>
      <webElementGuid>91b7c56b-9993-4845-a23f-d84fff803933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicyDetailsMainDiv&quot;)/div[@class=&quot;ISiWhiteCanvasHeader&quot;]/table[@id=&quot;acct_header_table&quot;]/tbody[1]/tr[1]/td[1]/button[@id=&quot;navButton&quot;]</value>
      <webElementGuid>c4c6da23-5c2d-4788-879f-0212bd213229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>14d7925b-cbc8-4129-98df-54a848bee0af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navButton']</value>
      <webElementGuid>e389961c-0b97-4909-8d30-832d99151458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='acct_header_table']/tbody/tr/td/button</value>
      <webElementGuid>1f698893-20e4-4a8f-99a4-bd45a847409b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading....'])[1]/following::button[1]</value>
      <webElementGuid>5bfa7c3c-0cf0-4f66-b09f-4a342ad4d21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send a Message to the Insured'])[1]/following::button[1]</value>
      <webElementGuid>33b5f9e6-da3d-486e-976c-a0c4527301f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='john.hughes@cornerops.com'])[1]/preceding::button[1]</value>
      <webElementGuid>1d8c3a5a-f648-41b3-94ff-75cf845c49d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MORE ↓']/parent::*</value>
      <webElementGuid>a2b28f97-5273-433d-9c32-ad37849f9ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a6f92415-5e67-4df5-9172-51919747606f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'navButton' and (text() = 'MORE ↓' or . = 'MORE ↓')]</value>
      <webElementGuid>6f8d92d5-dc82-479b-b681-e98c27cc29e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
