<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Recalculate</name>
   <tag></tag>
   <elementGuidId>b897b166-2122-44e2-8cc1-702aa013294c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEButtonISOReplacementCost_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='NOSAVEButtonISOReplacementCost_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c58a1a09-1562-439b-9509-107b44d554c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn buttonWidget ISiA-PrimaryButton</value>
      <webElementGuid>f99074aa-cec4-4fc1-a2df-edad5e87f72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62a3c6b9-cc92-4fd4-84f4-f4f67b1585de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if ((typeof this === 'undefined' || typeof this.id === 'undefined' || this.id=='' || DblClkTrap(this.id,'set'))) { LookupButtonClickJS('2201','1','reusableModalBody','https://alchemytest.cogisi.com/is/root/','1','ISO360');  };</value>
      <webElementGuid>956d0a6e-c54e-4416-b597-5196457d0437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEButtonISOReplacementCost_1</value>
      <webElementGuid>36a9ffe1-26bc-4f8c-9bf9-6bae332142dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEButtonISOReplacementCost_1</value>
      <webElementGuid>5d53aa3d-7914-47d3-8a46-e31d8abe6c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recalculate</value>
      <webElementGuid>4f9b3009-4141-480d-9a24-599ae4fd2a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEButtonISOReplacementCost_1&quot;)</value>
      <webElementGuid>a089eaba-d3b9-4060-afc4-829439981df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>03691dba-fdbe-4fea-8441-15d97ea73286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='NOSAVEButtonISOReplacementCost_1']</value>
      <webElementGuid>5b3b60ee-66a9-4d1c-8c97-2b145d633505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ISOReplacementCost_1']/div/div/button</value>
      <webElementGuid>109d9945-826b-40bc-bdc9-cc13066aadf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO 360Value Replacement Cost Calculation'])[1]/following::button[1]</value>
      <webElementGuid>0323fc90-ee75-41c9-9551-1a1a23e232e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replacement Cost'])[1]/following::button[1]</value>
      <webElementGuid>2c8bb1c9-a08a-4676-ab8c-699de00ea865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional Property Coverages'])[1]/preceding::button[1]</value>
      <webElementGuid>17f494dd-e9b2-4d9b-b1a4-54ee74c9a696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional Coverage List (Select All that apply)'])[1]/preceding::button[1]</value>
      <webElementGuid>96050dd3-4a71-443e-824c-76fdb1241414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recalculate']/parent::*</value>
      <webElementGuid>3473adbf-889b-488a-a2ab-95bf502786bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[3]/div/div/button</value>
      <webElementGuid>8e0aa1dc-f4d2-4445-b82a-873e7fc09b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'NOSAVEButtonISOReplacementCost_1' and @id = 'NOSAVEButtonISOReplacementCost_1' and (text() = 'Recalculate' or . = 'Recalculate')]</value>
      <webElementGuid>37d82e61-ea84-4669-bb53-c2628b4e6867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
