<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_NOSAVESELECTEDBUSINESS_1</name>
   <tag></tag>
   <elementGuidId>aabe0ccb-2e82-4dc4-9951-34a46149db1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NOSAVESELECTEDBUSINESS_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NOSAVESELECTEDBUSINESS_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffdf6e10-d16b-4c6b-bc6b-d3bef87779a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0d0e8fea-529a-49bc-95ea-a6b78e88365e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);CheckRequired(false);GlobalCheckDisable(this);</value>
      <webElementGuid>058ff3e5-fb9c-46be-bb58-533b17f4c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVESELECTEDBUSINESS_1</value>
      <webElementGuid>6fc58543-4ca1-48ce-991d-b2bd54b05ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>37d062ef-4320-4099-936d-ed0fd1366ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Wrapper-Left-SELECTEDBUSINESS_1&quot;)/table[@class=&quot;table table-borderless table-striped table-sm table-responsive-sm&quot;]/tbody[1]/tr[2]/td[1]/input[1]</value>
      <webElementGuid>b12fc935-30c0-44be-8904-760c2b257b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>51c09469-a263-4eb3-b944-4c29a98a834e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NOSAVESELECTEDBUSINESS_1']</value>
      <webElementGuid>40d8c685-d1f6-43ac-981e-23b4c0027dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-SELECTEDBUSINESS_1']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>f4e836f9-e8a5-4a51-b11d-2577a8f6d90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>664a39ca-916f-4d7b-ae0d-39d62535f005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVESELECTEDBUSINESS_1']</value>
      <webElementGuid>5a1aab17-349d-462a-8c29-28bbef5097b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
