<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEHasReinforcedSteel</name>
   <tag></tag>
   <elementGuidId>06588f79-84e3-4f24-acc3-19e16a83ccce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEHasReinforcedSteelNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEHasReinforcedSteelNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4301b36-f3ed-4942-8b33-866be761a2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ed4d3a12-6099-4ba5-ac7c-c34e1446337d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b5a429ec-3b55-4241-ad9e-aff9cb71dfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6a03c0c-3f7f-4807-a813-e0219b1031cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEHasReinforcedSteel</value>
      <webElementGuid>968ba842-c21e-43f5-ba78-d0dd9761c908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEHasReinforcedSteelNo</value>
      <webElementGuid>2adb8734-1d45-425b-848b-bde6b8b329d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>0f1567ef-119f-446e-985b-2120a0dcdc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this); </value>
      <webElementGuid>232100ca-4535-4c2e-9a3c-16f72e266849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>d6a3741a-8a2e-438d-80c8-b2636254c401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>  CheckRequired(false);</value>
      <webElementGuid>4e473b2e-05ec-4d5c-ac2c-e767301d03e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEHasReinforcedSteelNo&quot;)</value>
      <webElementGuid>c07f0f29-75f6-4341-8bae-cdb830420580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>cd2ee709-4f2b-41fe-9b93-b47fd2b9cc8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEHasReinforcedSteelNo']</value>
      <webElementGuid>e5288482-b339-41e3-abe9-5b0c615ac1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-HasReinforcedSteel']/div[2]/input</value>
      <webElementGuid>d32f0dde-5c17-4734-bd1f-de528921e8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[11]/div/div[2]/div[2]/input</value>
      <webElementGuid>86f38dee-bbd5-42b1-bb86-36481b408497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEHasReinforcedSteel' and @id = 'NOSAVEHasReinforcedSteelNo']</value>
      <webElementGuid>66dfc899-684f-40ea-b7f6-30e607c9ea6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
