<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applicant Suffix_NOSAVE-INDApplicantS_d9ac27</name>
   <tag></tag>
   <elementGuidId>4f3bcc63-0c36-48b5-9b68-e1417c8ea160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantSuffixzzzz1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantSuffixzzzz1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4027fd4-b298-495b-8fbd-5ab86f5d6491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>546816ea-2262-4fc7-8c5c-1c3980b34d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkForUpperCase(this);processAskLastName(this,'ApplicantSuffixzzzz1');</value>
      <webElementGuid>ef451606-5fd8-42a0-a5cc-b63433adb26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ISiA-Force-Uppercase</value>
      <webElementGuid>0862b9ad-3bf1-44b9-8d8a-6d046d247551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Suffix</value>
      <webElementGuid>87e8efb1-f0f7-4324-a053-99f12fce82c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVE-INDApplicantSuffixzzzz1</value>
      <webElementGuid>9fa26ab2-8f31-4aa7-b851-a9092e4a0873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantSuffixzzzz1</value>
      <webElementGuid>ac0aefae-3afe-4bcd-bde1-2dd460f6e023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3990fb0b-c359-4f39-89c7-e27171758003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantSuffixzzzz1&quot;)</value>
      <webElementGuid>d2911f34-8785-40ab-a757-d396c78413aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>95714e51-f11d-4f77-9863-41bfdba17d5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantSuffixzzzz1']</value>
      <webElementGuid>50ec30d2-06ba-4109-aebd-34ebba740c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-ApplicantSuffixzzzz1']/input</value>
      <webElementGuid>c08170c5-a78a-48c5-bab3-2e4e5000357b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/input</value>
      <webElementGuid>488b9603-7335-4c80-ba3c-124262a61e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Suffix' and @name = 'NOSAVE-INDApplicantSuffixzzzz1' and @id = 'ApplicantSuffixzzzz1']</value>
      <webElementGuid>6ff96d71-cd4b-4fca-b9cc-f6e657e10524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
