<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_NOSAVEDoesCultivation</name>
   <tag></tag>
   <elementGuidId>da6c6a13-2bf1-43a3-878d-ae1ce4af90d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEDoesCultivationNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEDoesCultivationNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa187d91-0f7d-4015-82b6-79a1387b399d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b80aeabc-2913-419e-836d-6b575748b516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>93188ada-ad1a-4ee0-a578-596e496c8a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68a02463-591a-4adf-b0f7-1841a4fafbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEDoesCultivation</value>
      <webElementGuid>3d60fd6d-c6ed-4ec7-92ad-b817dd3d303c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEDoesCultivationNo</value>
      <webElementGuid>a7569df6-65d4-4566-909a-b69d0c6bbdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>c775c60b-a88b-4b87-a254-d6bfc9deeb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);setIfPresent(this,'ProductsCultivated','','input');setIfPresent(this,'PercentCultivated','','input');  GlobalCheckDisable(this);</value>
      <webElementGuid>4e88d5b9-c45d-4369-8730-da4c7dfc1cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>61015ccc-44dd-4094-8490-1b104c8c3543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>17b8a4a3-8070-47bf-b780-fa62881d438b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEDoesCultivationNo&quot;)</value>
      <webElementGuid>de27afff-b734-4503-85df-67acc89e461d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>9c3f099a-4059-4cab-876a-6fd1a344d285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEDoesCultivationNo']</value>
      <webElementGuid>2d084545-c712-42f2-8062-14edb60db498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-DoesCultivation']/div[2]/input</value>
      <webElementGuid>a0226560-712d-4da1-b63a-7ec8797a26cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div[2]/input</value>
      <webElementGuid>f5a5f0a0-0b16-429f-8b8f-0d9945cfff80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEDoesCultivation' and @id = 'NOSAVEDoesCultivationNo']</value>
      <webElementGuid>f5c78556-f14b-4482-b750-d8912201c698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
