<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Term_NOSAVEagentSearchAgentCode</name>
   <tag></tag>
   <elementGuidId>f70da754-11e0-4f99-9b35-960de5c76cbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEagentSearchAgentCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEagentSearchAgentCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c29f2582-6f9c-4f8c-8671-3d6016f71309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1607219-f3ee-4efa-a82e-fbddd3ed84a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a45f9d27-d97b-415b-844c-fcc2d5e70a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEagentSearchAgentCode</value>
      <webElementGuid>70ec446e-c1cc-45a7-b98b-06e3928ae1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEagentSearchAgentCode</value>
      <webElementGuid>c606d262-3eb8-4899-92c3-d6227d7a91a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>CheckEntertedInputValue(this,'https://alchemytest.cogisi.com/is/', 'AgentCode', 'SubAgentCode');</value>
      <webElementGuid>2bc11cca-d704-4182-87ef-2ac1e574a5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEagentSearchAgentCode&quot;)</value>
      <webElementGuid>8a1c27b8-4f1d-4c9a-aced-a14a4e2a6064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>2adac75e-2f09-4c5c-8352-35b0a2c03d62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEagentSearchAgentCode']</value>
      <webElementGuid>59d19f9c-aee0-4905-a1d5-440d963348d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AgentLookUpModal']/div/div/div[2]/div/div/input</value>
      <webElementGuid>27528e54-3eff-40f4-be3f-4fa73ce0ec52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>f139d787-520d-498a-a7d3-9ff572476f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NOSAVEagentSearchAgentCode' and @id = 'NOSAVEagentSearchAgentCode']</value>
      <webElementGuid>a5721e70-0cdb-4286-b3c5-054d921c1951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
