<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No_NOSAVEHasAllLocAlarms</name>
   <tag></tag>
   <elementGuidId>1bf05377-8479-4676-84f4-29dd8cb9a61b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NOSAVEHasAllLocAlarmsYes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NOSAVEHasAllLocAlarmsYes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>740db26f-2f41-4c19-b2ed-c0458d0eca93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>fb5045f3-f8ed-42a7-89ad-74e0ea36dcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e4ccca57-4adb-4024-aa0c-d91789f8d201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>86cd756d-954a-44c2-8076-4e2e33d7f567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NOSAVEHasAllLocAlarms</value>
      <webElementGuid>bc62208b-0c2f-4d77-ab39-6f22b6549126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NOSAVEHasAllLocAlarmsYes</value>
      <webElementGuid>8de7ed61-6bda-414f-a01b-50e91ceaa45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>d15e24b7-fd7a-405a-a620-e93a076f972d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateYesNoValue(this);setIfPresent(this,'IsCompanyMonitored','','input');setIfPresent(this,'HasInteriorSensors','','input');setIfPresent(this,'IsExternalMonitored','','input');setIfPresent(this,'IsAlwaysOn','','input');  GlobalCheckDisable(this);</value>
      <webElementGuid>c64ee711-b3ba-4808-ae89-5f09c06ce718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>;</value>
      <webElementGuid>f89ffdd3-10a1-4a4c-a791-1edb56f6dc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value> GlobalCheckDisable(this);  CheckRequired(false);</value>
      <webElementGuid>09d691e4-76bb-4c8a-8cb0-9e0243959e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NOSAVEHasAllLocAlarmsYes&quot;)</value>
      <webElementGuid>2996b037-c548-4dc0-8697-7b9df0726466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alchemy/Page_/iframe_System FAQ_MainIS28test</value>
      <webElementGuid>09c240c8-a4c3-4456-8e61-3a8ea6ce1ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NOSAVEHasAllLocAlarmsYes']</value>
      <webElementGuid>6291932b-656f-4589-9a9f-c4d6ddb74b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-HasAllLocAlarms']/div/input</value>
      <webElementGuid>5291dd2d-a66d-4abb-8560-c6013accdb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[8]/div/div[2]/div/input</value>
      <webElementGuid>589f69be-5b38-4ba6-bb0e-3a27ffb6b19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'NOSAVEHasAllLocAlarms' and @id = 'NOSAVEHasAllLocAlarmsYes']</value>
      <webElementGuid>bd5db08a-8225-4f80-8f6e-0395e6b2e7f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
