<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_InterestAddress1xxxx1_1</name>
   <tag></tag>
   <elementGuidId>3fca3ad7-0e56-4bf8-907f-4c98ddc820fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InterestAddress1xxxx1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InterestAddress1xxxx1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37ef1961-f6b1-41a4-b2d9-188eea93fdbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abe804a6-866e-4bc5-9db3-6280e0b52eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a64c64c1-9983-4862-9e5f-b27b2bb7b611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address1*</value>
      <webElementGuid>6e4aac46-2dda-44d2-bd01-e00bfe5cb6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3054aaba-ddf9-473f-9477-10f3e506cfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InterestAddress1xxxx1_1</value>
      <webElementGuid>ecad7a33-4ebb-41df-b174-199826786a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InterestAddress1xxxx1_1</value>
      <webElementGuid>358c312c-2cfe-49a6-9a89-070ac86a7e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addressRemoveInvalid(this);USPSRealtimeAddressValidation('a82741540573558027i15151613s3902970422694160i54330','https://cypresstest.cogisi.com/is/','1701030','Interest','xxxx1_1','Address1',0,0);</value>
      <webElementGuid>03f93d26-2729-428b-b7b8-58508e17fe61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>document.getElementById('USPSCompleteAddressCheckedOnce-Interestxxxx1_1').value='0';</value>
      <webElementGuid>f6d9d0f9-274a-4273-82b7-eae423f691c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.select();</value>
      <webElementGuid>68f8ade5-c1b8-4bec-9b7e-edd7079d33af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InterestAddress1xxxx1_1&quot;)</value>
      <webElementGuid>2ff9b44a-e9fe-46b1-938d-6dd2ab364160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL DP/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>afc70b68-95b4-43d6-8859-d75cb32cc7a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InterestAddress1xxxx1_1']</value>
      <webElementGuid>0dcbf665-39f7-424c-9516-7917f8ba1040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-InterestAddress1xxxx1_1']/div/input[3]</value>
      <webElementGuid>10d70b4c-9e3e-4054-a3d0-0d343175a01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input[3]</value>
      <webElementGuid>985a9303-e6ef-43d8-91e1-21e91f39888f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Address1*' and @name = 'InterestAddress1xxxx1_1' and @id = 'InterestAddress1xxxx1_1']</value>
      <webElementGuid>b80daca4-0542-416e-877c-fdf3aa59d30c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
