<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DwellingLimit_1</name>
   <tag></tag>
   <elementGuidId>ac6c7c30-1547-4bdc-8c7e-12c5e366852b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DwellingLimit_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DwellingLimit_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c2dd608-a1f8-4c1b-b25d-9c4568cb0c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b011b0be-1a9c-4dac-b06a-a7cb72d713de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget </value>
      <webElementGuid>a343769d-d755-49c3-922d-7dadc27c9e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DwellingLimit_1</value>
      <webElementGuid>c87c0b8d-78d7-4ea9-af81-ee001f43dab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previousvalue</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>8303bdd1-f796-468c-a0cc-634fe8552d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b206783-9434-4c69-87ec-dcf2ba0f98e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabletohide</name>
      <type>Main</type>
      <value>DisableElement_DwellingLimit_1</value>
      <webElementGuid>53d24708-de77-4b79-adea-bd65669b3329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DwellingLimit_1</value>
      <webElementGuid>147857b1-b6e8-4b1d-bb19-c7c7c08e7005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>b6a9a093-72ab-4c9b-b581-7b9712a7ef88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);ConditionalOnChangeAlert(this,'UWQuoteCode,=,C;ISOReplacementCost_1,&lt;>,0;ISOReplacementCost_1,&lt;>,BLANK;AND','_1','Cov A change requires 360Value to be run again. Select Get Replacement Cost button to recalculate and provide updated amount.','false','false');  GlobalOnBlur();   CheckRequired(false);</value>
      <webElementGuid>4667e9bc-ef8e-49ce-bd4f-a3f6194296b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>  GlobalOnChange(); </value>
      <webElementGuid>a937b1d0-86c7-406b-b128-999de4247105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>e526b841-e76e-4585-bb80-b54c9dc6c06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>5000000.00</value>
      <webElementGuid>d5912530-822b-4b38-8966-91934d492254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>100000.00</value>
      <webElementGuid>bf5b714f-727a-4635-8544-645f47b9b5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dc7db833-4c9b-4c66-a7e5-7b00d704ab59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DwellingLimit_1&quot;)</value>
      <webElementGuid>ba05f9b7-335f-4d0c-ac38-a66dc0773c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO3-NOTUSED/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>4721e67f-b003-4698-be3d-35476d2f7084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DwellingLimit_1']</value>
      <webElementGuid>36cef33f-cf23-413f-b81e-3ea97f8bf4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Left-DwellingLimit_1']/div[2]/div/input</value>
      <webElementGuid>04a36fa9-039a-4083-816a-665cac199367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d18f3a50-09db-4831-ba37-f07f574d7a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DwellingLimit_1' and @id = 'DwellingLimit_1']</value>
      <webElementGuid>80bba6fd-93a8-4f9b-8f25-3af1f821b238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
