<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_ApplicantEmailzzzz1</name>
   <tag></tag>
   <elementGuidId>b741212d-9042-488b-9f85-ea510a259c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ApplicantEmailzzzz1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ApplicantEmailzzzz1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f204a59-a8e8-4d55-90f0-d2f5f03c07b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>877007ce-87ec-48f0-9f04-fd8e61e152b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b152753-2137-4997-90de-50f83aa97e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>1396c02a-6516-4964-b97e-f42df5e95c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantEmailzzzz1</value>
      <webElementGuid>fe38d440-9d9d-46e3-9090-772cb64dc1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>CheckEmail(this);  GlobalOnBlur(); </value>
      <webElementGuid>40cbaf92-4f58-4e27-b58f-be25eecb6310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantEmailzzzz1&quot;)</value>
      <webElementGuid>acc2e21c-9399-412f-9637-074d32877cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TX Evergreen HO6/Page_/iframe_Agent Transaction Report_MainIS21test</value>
      <webElementGuid>be5454c0-6341-473b-be7f-b39800420803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ApplicantEmailzzzz1']</value>
      <webElementGuid>45a69808-dbc5-4f16-a09a-7bf401e4d7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Wrapper-Right-ApplicantEmailzzzz1']/input</value>
      <webElementGuid>605a0e61-db7c-4ed8-a282-7fdf79bf90a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/input</value>
      <webElementGuid>e95068ab-8a98-4fb8-8e6f-392946efcc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ApplicantEmailzzzz1' and @id = 'ApplicantEmailzzzz1']</value>
      <webElementGuid>b6078761-1c99-4be3-beba-5fa92d973110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
