<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payroll_ClassCodePayroll_9</name>
   <tag></tag>
   <elementGuidId>56a1a968-8387-40ea-a1ca-dc507ae7c03b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ClassCodePayroll_9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ClassCodePayroll_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69b45008-6aae-452f-b353-495cdf8180b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93d26b5b-f7d4-494c-acc9-df32ac3d5634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control numberWidget</value>
      <webElementGuid>1a283b31-7649-4bee-b824-9cd6ce98b2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClassCodePayroll_1</value>
      <webElementGuid>775dc17c-e875-443f-aa86-78b13db25c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disablemessagetrigger</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c47fd471-7263-410c-a9c8-617ea1d70c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClassCodePayroll_1</value>
      <webElementGuid>2dc0d7c1-4d35-4257-86a8-d52bf2c35911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>isNumberJS(this);   CheckRequired(false);</value>
      <webElementGuid>ac39582c-05ca-4da2-8485-fae8458bbd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copyFieldValue(this,'NOSAVEPayroll_1'); </value>
      <webElementGuid>c98d4a84-1bb2-496f-8d09-978d003afe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>numbertype</name>
      <type>Main</type>
      <value>integer</value>
      <webElementGuid>7804deb6-280a-464c-b974-a3135875d781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>7afd3293-13c9-420c-8ec2-8a682e1081cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalplaces</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2f064c4-238d-448e-9822-38626a5e41e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClassCodePayroll_1&quot;)</value>
      <webElementGuid>f6ebdc1f-4bcf-4c3e-a15a-5449637cd9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FL GL/Page_/iframe_RTR Quotes_MainIS21test</value>
      <webElementGuid>f609dff4-0ced-41f4-a154-dda989f7f770</webElementGuid>
   </webElementProperties>
</WebElementEntity>
