<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AGENT CODE_userloginid</name>
   <tag></tag>
   <elementGuidId>1c1b637d-165f-4575-b1fa-13a0d5a32e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userloginid&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userloginid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d2f0f44-ceea-46bf-8746-af39c8891195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ISiTextBox ISiWideInput</value>
      <webElementGuid>26422ac7-d5f0-4024-8e07-2a59c9c903c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98b45976-13d7-48cc-a098-95bfe13a4428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userloginid</value>
      <webElementGuid>e26be396-e352-4414-9ae5-7cdf94f0aa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LogonForm&quot;)/table[1]/tbody[1]/tr[2]/td[@class=&quot;DarkBackground&quot;]/table[1]/tbody[1]/tr[2]/td[1]/input[@class=&quot;ISiTextBox ISiWideInput&quot;]</value>
      <webElementGuid>44279cf1-dc07-4891-aab1-d110f77be532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userloginid']</value>
      <webElementGuid>fb45a452-bc30-4440-9898-d9dc7b5f62d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LogonForm']/table/tbody/tr[2]/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>23f4e872-24ed-4959-9b96-0ee40eeac0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>15aa9d00-807d-4e2e-846c-34dd2e29f974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userloginid']</value>
      <webElementGuid>735165e2-d6af-4c9d-82b6-64cef797497d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
